package com.sblm.modelMP;


// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name="ACCION"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Accion  implements java.io.Serializable {


     private String idacc;
     private String desacc;
     private String grpacc;
     private Boolean habacc;

    public Accion() {
    }

	
    public Accion(String idacc) {
        this.idacc = idacc;
    }
    public Accion(String idacc, String desacc, String grpacc, Boolean habacc) {
       this.idacc = idacc;
       this.desacc = desacc;
       this.grpacc = grpacc;
       this.habacc = habacc;
    }
   
     @Id 
    
    @Column(name="IDACC", unique=true, nullable=false, length=4)
    public String getIdacc() {
        return this.idacc;
    }
    
    public void setIdacc(String idacc) {
        this.idacc = idacc;
    }
    
    @Column(name="DESACC", length=50)
    public String getDesacc() {
        return this.desacc;
    }
    
    public void setDesacc(String desacc) {
        this.desacc = desacc;
    }
    
    @Column(name="GRPACC", length=20)
    public String getGrpacc() {
        return this.grpacc;
    }
    
    public void setGrpacc(String grpacc) {
        this.grpacc = grpacc;
    }
    
    @Column(name="HABACC")
    public Boolean getHabacc() {
        return this.habacc;
    }
    
    public void setHabacc(Boolean habacc) {
        this.habacc = habacc;
    }




}


