package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aplicacion generated by hbm2java
 */
@Entity
@Table(name="APLICACION"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Aplicacion  implements java.io.Serializable {


     private String idapp;
     private String desapp;
     private String useapp;
     private String catapp;
     private String usrdbapp;
     private String pswdbapp;
     private String roldb;
     private Boolean habapp;

    public Aplicacion() {
    }

	
    public Aplicacion(String idapp) {
        this.idapp = idapp;
    }
    public Aplicacion(String idapp, String desapp, String useapp, String catapp, String usrdbapp, String pswdbapp, String roldb, Boolean habapp) {
       this.idapp = idapp;
       this.desapp = desapp;
       this.useapp = useapp;
       this.catapp = catapp;
       this.usrdbapp = usrdbapp;
       this.pswdbapp = pswdbapp;
       this.roldb = roldb;
       this.habapp = habapp;
    }
   
     @Id 
    
    @Column(name="IDAPP", unique=true, nullable=false, length=10)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }
    
    @Column(name="DESAPP", length=100)
    public String getDesapp() {
        return this.desapp;
    }
    
    public void setDesapp(String desapp) {
        this.desapp = desapp;
    }
    
    @Column(name="USEAPP", length=100)
    public String getUseapp() {
        return this.useapp;
    }
    
    public void setUseapp(String useapp) {
        this.useapp = useapp;
    }
    
    @Column(name="CATAPP", length=20)
    public String getCatapp() {
        return this.catapp;
    }
    
    public void setCatapp(String catapp) {
        this.catapp = catapp;
    }
    
    @Column(name="USRDBAPP", length=20)
    public String getUsrdbapp() {
        return this.usrdbapp;
    }
    
    public void setUsrdbapp(String usrdbapp) {
        this.usrdbapp = usrdbapp;
    }
    
    @Column(name="PSWDBAPP", length=20)
    public String getPswdbapp() {
        return this.pswdbapp;
    }
    
    public void setPswdbapp(String pswdbapp) {
        this.pswdbapp = pswdbapp;
    }
    
    @Column(name="ROLDB", length=20)
    public String getRoldb() {
        return this.roldb;
    }
    
    public void setRoldb(String roldb) {
        this.roldb = roldb;
    }
    
    @Column(name="HABAPP")
    public Boolean getHabapp() {
        return this.habapp;
    }
    
    public void setHabapp(Boolean habapp) {
        this.habapp = habapp;
    }




}


