package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="AREA"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Area  implements java.io.Serializable {


     private String idare;
     private String desare;
     private String sigare;
     private Boolean opcareext;
     private String dirare;
     private String refare;
     private String conare;
     private String carare;
     private String telare;
     private String anxare;
     private String faxare;
     private String webare;
     private Boolean habare;

    public Area() {
    }

	
    public Area(String idare) {
        this.idare = idare;
    }
    public Area(String idare, String desare, String sigare, Boolean opcareext, String dirare, String refare, String conare, String carare, String telare, String anxare, String faxare, String webare, Boolean habare) {
       this.idare = idare;
       this.desare = desare;
       this.sigare = sigare;
       this.opcareext = opcareext;
       this.dirare = dirare;
       this.refare = refare;
       this.conare = conare;
       this.carare = carare;
       this.telare = telare;
       this.anxare = anxare;
       this.faxare = faxare;
       this.webare = webare;
       this.habare = habare;
    }
   
     @Id 
    
    @Column(name="IDARE", unique=true, nullable=false, length=8)
    public String getIdare() {
        return this.idare;
    }
    
    public void setIdare(String idare) {
        this.idare = idare;
    }
    
    @Column(name="DESARE", length=80)
    public String getDesare() {
        return this.desare;
    }
    
    public void setDesare(String desare) {
        this.desare = desare;
    }
    
    @Column(name="SIGARE", length=24)
    public String getSigare() {
        return this.sigare;
    }
    
    public void setSigare(String sigare) {
        this.sigare = sigare;
    }
    
    @Column(name="OPCAREEXT")
    public Boolean getOpcareext() {
        return this.opcareext;
    }
    
    public void setOpcareext(Boolean opcareext) {
        this.opcareext = opcareext;
    }
    
    @Column(name="DIRARE", length=100)
    public String getDirare() {
        return this.dirare;
    }
    
    public void setDirare(String dirare) {
        this.dirare = dirare;
    }
    
    @Column(name="REFARE", length=100)
    public String getRefare() {
        return this.refare;
    }
    
    public void setRefare(String refare) {
        this.refare = refare;
    }
    
    @Column(name="CONARE", length=50)
    public String getConare() {
        return this.conare;
    }
    
    public void setConare(String conare) {
        this.conare = conare;
    }
    
    @Column(name="CARARE", length=30)
    public String getCarare() {
        return this.carare;
    }
    
    public void setCarare(String carare) {
        this.carare = carare;
    }
    
    @Column(name="TELARE", length=10)
    public String getTelare() {
        return this.telare;
    }
    
    public void setTelare(String telare) {
        this.telare = telare;
    }
    
    @Column(name="ANXARE", length=10)
    public String getAnxare() {
        return this.anxare;
    }
    
    public void setAnxare(String anxare) {
        this.anxare = anxare;
    }
    
    @Column(name="FAXARE", length=10)
    public String getFaxare() {
        return this.faxare;
    }
    
    public void setFaxare(String faxare) {
        this.faxare = faxare;
    }
    
    @Column(name="WEBARE", length=100)
    public String getWebare() {
        return this.webare;
    }
    
    public void setWebare(String webare) {
        this.webare = webare;
    }
    
    @Column(name="HABARE")
    public Boolean getHabare() {
        return this.habare;
    }
    
    public void setHabare(Boolean habare) {
        this.habare = habare;
    }




}


