package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detdonacion generated by hbm2java
 */
@Entity
@Table(name="DETDONACION"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Detdonacion  implements java.io.Serializable {


     private String iddetdnc;
     private Donacion donacion;
     private String idsubtip;
     private String idunimed;
     private String desdetdnc;
     private Integer cnddetdnc;
     private BigDecimal mtodetdnc;

    public Detdonacion() {
    }

	
    public Detdonacion(String iddetdnc) {
        this.iddetdnc = iddetdnc;
    }
    public Detdonacion(String iddetdnc, Donacion donacion, String idsubtip, String idunimed, String desdetdnc, Integer cnddetdnc, BigDecimal mtodetdnc) {
       this.iddetdnc = iddetdnc;
       this.donacion = donacion;
       this.idsubtip = idsubtip;
       this.idunimed = idunimed;
       this.desdetdnc = desdetdnc;
       this.cnddetdnc = cnddetdnc;
       this.mtodetdnc = mtodetdnc;
    }
   
     @Id 
    
    @Column(name="IDDETDNC", unique=true, nullable=false, length=22)
    public String getIddetdnc() {
        return this.iddetdnc;
    }
    
    public void setIddetdnc(String iddetdnc) {
        this.iddetdnc = iddetdnc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDDNC")
    public Donacion getDonacion() {
        return this.donacion;
    }
    
    public void setDonacion(Donacion donacion) {
        this.donacion = donacion;
    }
    
    @Column(name="IDSUBTIP", length=6)
    public String getIdsubtip() {
        return this.idsubtip;
    }
    
    public void setIdsubtip(String idsubtip) {
        this.idsubtip = idsubtip;
    }
    
    @Column(name="IDUNIMED", length=4)
    public String getIdunimed() {
        return this.idunimed;
    }
    
    public void setIdunimed(String idunimed) {
        this.idunimed = idunimed;
    }
    
    @Column(name="DESDETDNC", length=200)
    public String getDesdetdnc() {
        return this.desdetdnc;
    }
    
    public void setDesdetdnc(String desdetdnc) {
        this.desdetdnc = desdetdnc;
    }
    
    @Column(name="CNDDETDNC")
    public Integer getCnddetdnc() {
        return this.cnddetdnc;
    }
    
    public void setCnddetdnc(Integer cnddetdnc) {
        this.cnddetdnc = cnddetdnc;
    }
    
    @Column(name="MTODETDNC", precision=10)
    public BigDecimal getMtodetdnc() {
        return this.mtodetdnc;
    }
    
    public void setMtodetdnc(BigDecimal mtodetdnc) {
        this.mtodetdnc = mtodetdnc;
    }




}


