package com.sblm.modelMP;


// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name="DOCUMENTO"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Documento  implements java.io.Serializable {


     private String iddoc;
     private String idare;
     private String idtipdoc;
     private String idasn;
     private String ident;
     private String idrmt;
     private String iddocmst;
     private String numtipdoc;
     private String titdoc;
     private String numrefint;
     private String numrefext;
     private Date fecdoc;
     private String desdoc;
     private Integer durdoc;
     private Boolean opcdoccfd;
     private Boolean opcdocprt;
     private Boolean opcdocext;
     private Boolean opcrsbent;
     private Boolean opcanldoc;
     private String usrins;
     private Date fecins;
     private String usrupd;
     private Date fecupd;
     private String desasn;
     private String desrmt;
     private String ejedoc;
     private Set<Flujodoc> flujodocs = new HashSet<Flujodoc>(0);

    public Documento() {
    }

	
    public Documento(String iddoc) {
        this.iddoc = iddoc;
    }
    public Documento(String iddoc, String idare, String idtipdoc, String idasn, String ident, String idrmt, String iddocmst, String numtipdoc, String titdoc, String numrefint, String numrefext, Date fecdoc, String desdoc, Integer durdoc, Boolean opcdoccfd, Boolean opcdocprt, Boolean opcdocext, Boolean opcrsbent, Boolean opcanldoc, String usrins, Date fecins, String usrupd, Date fecupd, String desasn, String desrmt, String ejedoc, Set<Flujodoc> flujodocs) {
       this.iddoc = iddoc;
       this.idare = idare;
       this.idtipdoc = idtipdoc;
       this.idasn = idasn;
       this.ident = ident;
       this.idrmt = idrmt;
       this.iddocmst = iddocmst;
       this.numtipdoc = numtipdoc;
       this.titdoc = titdoc;
       this.numrefint = numrefint;
       this.numrefext = numrefext;
       this.fecdoc = fecdoc;
       this.desdoc = desdoc;
       this.durdoc = durdoc;
       this.opcdoccfd = opcdoccfd;
       this.opcdocprt = opcdocprt;
       this.opcdocext = opcdocext;
       this.opcrsbent = opcrsbent;
       this.opcanldoc = opcanldoc;
       this.usrins = usrins;
       this.fecins = fecins;
       this.usrupd = usrupd;
       this.fecupd = fecupd;
       this.desasn = desasn;
       this.desrmt = desrmt;
       this.ejedoc = ejedoc;
       this.flujodocs = flujodocs;
    }
   
     @Id 
    
    @Column(name="IDDOC", unique=true, nullable=false, length=20)
    public String getIddoc() {
        return this.iddoc;
    }
    
    public void setIddoc(String iddoc) {
        this.iddoc = iddoc;
    }
    
    @Column(name="IDARE", length=8)
    public String getIdare() {
        return this.idare;
    }
    
    public void setIdare(String idare) {
        this.idare = idare;
    }
    
    @Column(name="IDTIPDOC", length=4)
    public String getIdtipdoc() {
        return this.idtipdoc;
    }
    
    public void setIdtipdoc(String idtipdoc) {
        this.idtipdoc = idtipdoc;
    }
    
    @Column(name="IDASN", length=4)
    public String getIdasn() {
        return this.idasn;
    }
    
    public void setIdasn(String idasn) {
        this.idasn = idasn;
    }
    
    @Column(name="IDENT", length=8)
    public String getIdent() {
        return this.ident;
    }
    
    public void setIdent(String ident) {
        this.ident = ident;
    }
    
    @Column(name="IDRMT", length=12)
    public String getIdrmt() {
        return this.idrmt;
    }
    
    public void setIdrmt(String idrmt) {
        this.idrmt = idrmt;
    }
    
    @Column(name="IDDOCMST", length=20)
    public String getIddocmst() {
        return this.iddocmst;
    }
    
    public void setIddocmst(String iddocmst) {
        this.iddocmst = iddocmst;
    }
    
    @Column(name="NUMTIPDOC", length=10)
    public String getNumtipdoc() {
        return this.numtipdoc;
    }
    
    public void setNumtipdoc(String numtipdoc) {
        this.numtipdoc = numtipdoc;
    }
    
    @Column(name="TITDOC", length=100)
    public String getTitdoc() {
        return this.titdoc;
    }
    
    public void setTitdoc(String titdoc) {
        this.titdoc = titdoc;
    }
    
    @Column(name="NUMREFINT", length=20)
    public String getNumrefint() {
        return this.numrefint;
    }
    
    public void setNumrefint(String numrefint) {
        this.numrefint = numrefint;
    }
    
    @Column(name="NUMREFEXT", length=20)
    public String getNumrefext() {
        return this.numrefext;
    }
    
    public void setNumrefext(String numrefext) {
        this.numrefext = numrefext;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECDOC", length=23)
    public Date getFecdoc() {
        return this.fecdoc;
    }
    
    public void setFecdoc(Date fecdoc) {
        this.fecdoc = fecdoc;
    }
    
    @Column(name="DESDOC", length=250)
    public String getDesdoc() {
        return this.desdoc;
    }
    
    public void setDesdoc(String desdoc) {
        this.desdoc = desdoc;
    }
    
    @Column(name="DURDOC")
    public Integer getDurdoc() {
        return this.durdoc;
    }
    
    public void setDurdoc(Integer durdoc) {
        this.durdoc = durdoc;
    }
    
    @Column(name="OPCDOCCFD")
    public Boolean getOpcdoccfd() {
        return this.opcdoccfd;
    }
    
    public void setOpcdoccfd(Boolean opcdoccfd) {
        this.opcdoccfd = opcdoccfd;
    }
    
    @Column(name="OPCDOCPRT")
    public Boolean getOpcdocprt() {
        return this.opcdocprt;
    }
    
    public void setOpcdocprt(Boolean opcdocprt) {
        this.opcdocprt = opcdocprt;
    }
    
    @Column(name="OPCDOCEXT")
    public Boolean getOpcdocext() {
        return this.opcdocext;
    }
    
    public void setOpcdocext(Boolean opcdocext) {
        this.opcdocext = opcdocext;
    }
    
    @Column(name="OPCRSBENT")
    public Boolean getOpcrsbent() {
        return this.opcrsbent;
    }
    
    public void setOpcrsbent(Boolean opcrsbent) {
        this.opcrsbent = opcrsbent;
    }
    
    @Column(name="OPCANLDOC")
    public Boolean getOpcanldoc() {
        return this.opcanldoc;
    }
    
    public void setOpcanldoc(Boolean opcanldoc) {
        this.opcanldoc = opcanldoc;
    }
    
    @Column(name="USRINS", length=20)
    public String getUsrins() {
        return this.usrins;
    }
    
    public void setUsrins(String usrins) {
        this.usrins = usrins;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECINS", length=23)
    public Date getFecins() {
        return this.fecins;
    }
    
    public void setFecins(Date fecins) {
        this.fecins = fecins;
    }
    
    @Column(name="USRUPD", length=20)
    public String getUsrupd() {
        return this.usrupd;
    }
    
    public void setUsrupd(String usrupd) {
        this.usrupd = usrupd;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECUPD", length=23)
    public Date getFecupd() {
        return this.fecupd;
    }
    
    public void setFecupd(Date fecupd) {
        this.fecupd = fecupd;
    }
    
    @Column(name="DESASN", length=100)
    public String getDesasn() {
        return this.desasn;
    }
    
    public void setDesasn(String desasn) {
        this.desasn = desasn;
    }
    
    @Column(name="DESRMT", length=100)
    public String getDesrmt() {
        return this.desrmt;
    }
    
    public void setDesrmt(String desrmt) {
        this.desrmt = desrmt;
    }
    
    @Column(name="EJEDOC", length=4)
    public String getEjedoc() {
        return this.ejedoc;
    }
    
    public void setEjedoc(String ejedoc) {
        this.ejedoc = ejedoc;
    }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<Flujodoc> getFlujodocs() {
		return this.flujodocs;
	}

	public void setFlujodocs(Set<Flujodoc> flujodocs) {
		this.flujodocs = flujodocs;
	}


}


