package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donacion generated by hbm2java
 */
@Entity
@Table(name="DONACION"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Donacion  implements java.io.Serializable {


     private String iddnc;
     private String idemp;
     private String idare;
     private String idtip;
     private Date fecnea;
     private String numnea;
     private Set<Detdonacion> detdonacions = new HashSet<Detdonacion>(0);

    public Donacion() {
    }

	
    public Donacion(String iddnc) {
        this.iddnc = iddnc;
    }
    public Donacion(String iddnc, String idemp, String idare, String idtip, Date fecnea, String numnea, Set<Detdonacion> detdonacions) {
       this.iddnc = iddnc;
       this.idemp = idemp;
       this.idare = idare;
       this.idtip = idtip;
       this.fecnea = fecnea;
       this.numnea = numnea;
       this.detdonacions = detdonacions;
    }
   
     @Id 
    
    @Column(name="IDDNC", unique=true, nullable=false, length=18)
    public String getIddnc() {
        return this.iddnc;
    }
    
    public void setIddnc(String iddnc) {
        this.iddnc = iddnc;
    }
    
    @Column(name="IDEMP", length=8)
    public String getIdemp() {
        return this.idemp;
    }
    
    public void setIdemp(String idemp) {
        this.idemp = idemp;
    }
    
    @Column(name="IDARE", length=8)
    public String getIdare() {
        return this.idare;
    }
    
    public void setIdare(String idare) {
        this.idare = idare;
    }
    
    @Column(name="IDTIP", length=4)
    public String getIdtip() {
        return this.idtip;
    }
    
    public void setIdtip(String idtip) {
        this.idtip = idtip;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECNEA", length=23)
    public Date getFecnea() {
        return this.fecnea;
    }
    
    public void setFecnea(Date fecnea) {
        this.fecnea = fecnea;
    }
    
    @Column(name="NUMNEA", length=10)
    public String getNumnea() {
        return this.numnea;
    }
    
    public void setNumnea(String numnea) {
        this.numnea = numnea;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="donacion")
    public Set<Detdonacion> getDetdonacions() {
        return this.detdonacions;
    }
    
    public void setDetdonacions(Set<Detdonacion> detdonacions) {
        this.detdonacions = detdonacions;
    }




}


