package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="ESTADO"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Estado  implements java.io.Serializable {


     private String idest;
     private String desest;
     private String grpest;

    public Estado() {
    }

	
    public Estado(String idest) {
        this.idest = idest;
    }
    public Estado(String idest, String desest, String grpest) {
       this.idest = idest;
       this.desest = desest;
       this.grpest = grpest;
    }
   
     @Id 
    
    @Column(name="IDEST", unique=true, nullable=false, length=4)
    public String getIdest() {
        return this.idest;
    }
    
    public void setIdest(String idest) {
        this.idest = idest;
    }
    
    @Column(name="DESEST", length=50)
    public String getDesest() {
        return this.desest;
    }
    
    public void setDesest(String desest) {
        this.desest = desest;
    }
    
    @Column(name="GRPEST", length=20)
    public String getGrpest() {
        return this.grpest;
    }
    
    public void setGrpest(String grpest) {
        this.grpest = grpest;
    }




}


