package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Flujodoc generated by hbm2java
 */
@Entity
@Table(name="FLUJODOC"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Flujodoc  implements java.io.Serializable {


     private String idflj;
     private String idacc;
     private String numflj;
     private String idareori;
     private String idaredes;
     private Boolean opcogndoc;
     private String numrcpdes;
     private String numfol;
     private Character opcestflj;
     private Date fecenvdoc;
     private Date horenvdoc;
     private Date fecrcpdoc;
     private Date horrcpdoc;
     private Date fecestdoc;
     private String obsestflj;
     private String usrinsflj;
     private String usrupdflj;
     private Documento documento;

    public Flujodoc() {
    }

	
    public Flujodoc(String idflj) {
        this.idflj = idflj;
    }
    public Flujodoc(String idflj, String idacc, String numflj, String idareori, String idaredes, Boolean opcogndoc, String numrcpdes, String numfol, Character opcestflj, Date fecenvdoc, Date horenvdoc, Date fecrcpdoc, Date horrcpdoc, Date fecestdoc, String obsestflj, String usrinsflj, String usrupdflj, Documento documento) {
       this.idflj = idflj;
       this.idacc = idacc;
       this.numflj = numflj;
       this.idareori = idareori;
       this.idaredes = idaredes;
       this.opcogndoc = opcogndoc;
       this.numrcpdes = numrcpdes;
       this.numfol = numfol;
       this.opcestflj = opcestflj;
       this.fecenvdoc = fecenvdoc;
       this.horenvdoc = horenvdoc;
       this.fecrcpdoc = fecrcpdoc;
       this.horrcpdoc = horrcpdoc;
       this.fecestdoc = fecestdoc;
       this.obsestflj = obsestflj;
       this.usrinsflj = usrinsflj;
       this.usrupdflj = usrupdflj;
       this.documento = documento;
       
    }
   
	@Id 
    
    @Column(name="IDFLJ", unique=true, nullable=false, length=24)
    public String getIdflj() {
        return this.idflj;
    }
    
    public void setIdflj(String idflj) {
        this.idflj = idflj;
    }

    
    @Column(name="IDACC", length=4)
    public String getIdacc() {
        return this.idacc;
    }
    
    public void setIdacc(String idacc) {
        this.idacc = idacc;
    }
    
    @Column(name="NUMFLJ", length=2)
    public String getNumflj() {
        return this.numflj;
    }
    
    public void setNumflj(String numflj) {
        this.numflj = numflj;
    }
    
    @Column(name="IDAREORI", length=8)
    public String getIdareori() {
        return this.idareori;
    }
    
    public void setIdareori(String idareori) {
        this.idareori = idareori;
    }
    
    @Column(name="IDAREDES", length=8)
    public String getIdaredes() {
        return this.idaredes;
    }
    
    public void setIdaredes(String idaredes) {
        this.idaredes = idaredes;
    }
    
    @Column(name="OPCOGNDOC")
    public Boolean getOpcogndoc() {
        return this.opcogndoc;
    }
    
    public void setOpcogndoc(Boolean opcogndoc) {
        this.opcogndoc = opcogndoc;
    }
    
    @Column(name="NUMRCPDES", length=10)
    public String getNumrcpdes() {
        return this.numrcpdes;
    }
    
    public void setNumrcpdes(String numrcpdes) {
        this.numrcpdes = numrcpdes;
    }
    
    @Column(name="NUMFOL", length=4)
    public String getNumfol() {
        return this.numfol;
    }
    
    public void setNumfol(String numfol) {
        this.numfol = numfol;
    }
    
    @Column(name="OPCESTFLJ", length=1)
    public Character getOpcestflj() {
        return this.opcestflj;
    }
    
    public void setOpcestflj(Character opcestflj) {
        this.opcestflj = opcestflj;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECENVDOC", length=23)
    public Date getFecenvdoc() {
        return this.fecenvdoc;
    }
    
    public void setFecenvdoc(Date fecenvdoc) {
        this.fecenvdoc = fecenvdoc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HORENVDOC", length=23)
    public Date getHorenvdoc() {
        return this.horenvdoc;
    }
    
    public void setHorenvdoc(Date horenvdoc) {
        this.horenvdoc = horenvdoc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECRCPDOC", length=23)
    public Date getFecrcpdoc() {
        return this.fecrcpdoc;
    }
    
    public void setFecrcpdoc(Date fecrcpdoc) {
        this.fecrcpdoc = fecrcpdoc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HORRCPDOC", length=23)
    public Date getHorrcpdoc() {
        return this.horrcpdoc;
    }
    
    public void setHorrcpdoc(Date horrcpdoc) {
        this.horrcpdoc = horrcpdoc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECESTDOC", length=23)
    public Date getFecestdoc() {
        return this.fecestdoc;
    }
    
    public void setFecestdoc(Date fecestdoc) {
        this.fecestdoc = fecestdoc;
    }
    
    @Column(name="OBSESTFLJ")
    public String getObsestflj() {
        return this.obsestflj;
    }
    
    public void setObsestflj(String obsestflj) {
        this.obsestflj = obsestflj;
    }
    
    @Column(name="USRINSFLJ", length=20)
    public String getUsrinsflj() {
        return this.usrinsflj;
    }
    
    public void setUsrinsflj(String usrinsflj) {
        this.usrinsflj = usrinsflj;
    }
    
    @Column(name="USRUPDFLJ", length=20)
    public String getUsrupdflj() {
        return this.usrupdflj;
    }
    
    public void setUsrupdflj(String usrupdflj) {
        this.usrupdflj = usrupdflj;
    }


    
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDOC")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}
    
	
	
}


