package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Negociacion generated by hbm2java
 */
@Entity
@Table(name="NEGOCIACION"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Negociacion  implements java.io.Serializable {


     private String idngc;
     private Empresa empresa;
     private String idest;
     private String idrst;
     private Date feciningc;
     private Boolean dondin;
     private Boolean donbie;
     private Boolean donsrv;
     private String desngc;
     private Date fecterngc;
     private String docenvngc;
     private Boolean crtagr;
     private Boolean ctfdon;
     private Boolean habngc;

    public Negociacion() {
    }

	
    public Negociacion(String idngc) {
        this.idngc = idngc;
    }
    public Negociacion(String idngc, Empresa empresa, String idest, String idrst, Date feciningc, Boolean dondin, Boolean donbie, Boolean donsrv, String desngc, Date fecterngc, String docenvngc, Boolean crtagr, Boolean ctfdon, Boolean habngc) {
       this.idngc = idngc;
       this.empresa = empresa;
       this.idest = idest;
       this.idrst = idrst;
       this.feciningc = feciningc;
       this.dondin = dondin;
       this.donbie = donbie;
       this.donsrv = donsrv;
       this.desngc = desngc;
       this.fecterngc = fecterngc;
       this.docenvngc = docenvngc;
       this.crtagr = crtagr;
       this.ctfdon = ctfdon;
       this.habngc = habngc;
    }
   
     @Id 
    
    @Column(name="IDNGC", unique=true, nullable=false, length=14)
    public String getIdngc() {
        return this.idngc;
    }
    
    public void setIdngc(String idngc) {
        this.idngc = idngc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDEMP")
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    
    @Column(name="IDEST", length=4)
    public String getIdest() {
        return this.idest;
    }
    
    public void setIdest(String idest) {
        this.idest = idest;
    }
    
    @Column(name="IDRST", length=4)
    public String getIdrst() {
        return this.idrst;
    }
    
    public void setIdrst(String idrst) {
        this.idrst = idrst;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECININGC", length=23)
    public Date getFeciningc() {
        return this.feciningc;
    }
    
    public void setFeciningc(Date feciningc) {
        this.feciningc = feciningc;
    }
    
    @Column(name="DONDIN")
    public Boolean getDondin() {
        return this.dondin;
    }
    
    public void setDondin(Boolean dondin) {
        this.dondin = dondin;
    }
    
    @Column(name="DONBIE")
    public Boolean getDonbie() {
        return this.donbie;
    }
    
    public void setDonbie(Boolean donbie) {
        this.donbie = donbie;
    }
    
    @Column(name="DONSRV")
    public Boolean getDonsrv() {
        return this.donsrv;
    }
    
    public void setDonsrv(Boolean donsrv) {
        this.donsrv = donsrv;
    }
    
    @Column(name="DESNGC", length=250)
    public String getDesngc() {
        return this.desngc;
    }
    
    public void setDesngc(String desngc) {
        this.desngc = desngc;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECTERNGC", length=23)
    public Date getFecterngc() {
        return this.fecterngc;
    }
    
    public void setFecterngc(Date fecterngc) {
        this.fecterngc = fecterngc;
    }
    
    @Column(name="DOCENVNGC", length=100)
    public String getDocenvngc() {
        return this.docenvngc;
    }
    
    public void setDocenvngc(String docenvngc) {
        this.docenvngc = docenvngc;
    }
    
    @Column(name="CRTAGR")
    public Boolean getCrtagr() {
        return this.crtagr;
    }
    
    public void setCrtagr(Boolean crtagr) {
        this.crtagr = crtagr;
    }
    
    @Column(name="CTFDON")
    public Boolean getCtfdon() {
        return this.ctfdon;
    }
    
    public void setCtfdon(Boolean ctfdon) {
        this.ctfdon = ctfdon;
    }
    
    @Column(name="HABNGC")
    public Boolean getHabngc() {
        return this.habngc;
    }
    
    public void setHabngc(Boolean habngc) {
        this.habngc = habngc;
    }




}


