package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name="PERFIL"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Perfil  implements java.io.Serializable {


     private String idprf;
     private String idusr;
     private String idare;
     private String idapp;
     private String ejeprf;
     private Date feciniprf;
     private Date fecterprf;
     private String motterprf;
     private Boolean habprf;
     private Character levusr;

    public Perfil() {
    }

	
    public Perfil(String idprf) {
        this.idprf = idprf;
    }
    public Perfil(String idprf, String idusr, String idare, String idapp, String ejeprf, Date feciniprf, Date fecterprf, String motterprf, Boolean habprf, Character levusr) {
       this.idprf = idprf;
       this.idusr = idusr;
       this.idare = idare;
       this.idapp = idapp;
       this.ejeprf = ejeprf;
       this.feciniprf = feciniprf;
       this.fecterprf = fecterprf;
       this.motterprf = motterprf;
       this.habprf = habprf;
       this.levusr = levusr;
    }
   
     @Id 
    
    @Column(name="IDPRF", unique=true, nullable=false, length=24)
    public String getIdprf() {
        return this.idprf;
    }
    
    public void setIdprf(String idprf) {
        this.idprf = idprf;
    }
    
    @Column(name="IDUSR", length=20)
    public String getIdusr() {
        return this.idusr;
    }
    
    public void setIdusr(String idusr) {
        this.idusr = idusr;
    }
    
    @Column(name="IDARE", length=8)
    public String getIdare() {
        return this.idare;
    }
    
    public void setIdare(String idare) {
        this.idare = idare;
    }
    
    @Column(name="IDAPP", length=4)
    public String getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(String idapp) {
        this.idapp = idapp;
    }
    
    @Column(name="EJEPRF", length=4)
    public String getEjeprf() {
        return this.ejeprf;
    }
    
    public void setEjeprf(String ejeprf) {
        this.ejeprf = ejeprf;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECINIPRF", length=23)
    public Date getFeciniprf() {
        return this.feciniprf;
    }
    
    public void setFeciniprf(Date feciniprf) {
        this.feciniprf = feciniprf;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECTERPRF", length=23)
    public Date getFecterprf() {
        return this.fecterprf;
    }
    
    public void setFecterprf(Date fecterprf) {
        this.fecterprf = fecterprf;
    }
    
    @Column(name="MOTTERPRF", length=50)
    public String getMotterprf() {
        return this.motterprf;
    }
    
    public void setMotterprf(String motterprf) {
        this.motterprf = motterprf;
    }
    
    @Column(name="HABPRF")
    public Boolean getHabprf() {
        return this.habprf;
    }
    
    public void setHabprf(Boolean habprf) {
        this.habprf = habprf;
    }
    
    @Column(name="LEVUSR", length=1)
    public Character getLevusr() {
        return this.levusr;
    }
    
    public void setLevusr(Character levusr) {
        this.levusr = levusr;
    }




}


