package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Remitente generated by hbm2java
 */
@Entity
@Table(name="REMITENTE"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Remitente  implements java.io.Serializable {


     private String idrmt;
     private String idare;
     private String apprmt;
     private String apmrmt;
     private String nomrmt;
     private String sigrmt;
     private Boolean dftrmt;

    public Remitente() {
    }

	
    public Remitente(String idrmt) {
        this.idrmt = idrmt;
    }
    public Remitente(String idrmt, String idare, String apprmt, String apmrmt, String nomrmt, String sigrmt, Boolean dftrmt) {
       this.idrmt = idrmt;
       this.idare = idare;
       this.apprmt = apprmt;
       this.apmrmt = apmrmt;
       this.nomrmt = nomrmt;
       this.sigrmt = sigrmt;
       this.dftrmt = dftrmt;
    }
   
     @Id 
    
    @Column(name="IDRMT", unique=true, nullable=false, length=12)
    public String getIdrmt() {
        return this.idrmt;
    }
    
    public void setIdrmt(String idrmt) {
        this.idrmt = idrmt;
    }
    
    @Column(name="IDARE", length=8)
    public String getIdare() {
        return this.idare;
    }
    
    public void setIdare(String idare) {
        this.idare = idare;
    }
    
    @Column(name="APPRMT", length=30)
    public String getApprmt() {
        return this.apprmt;
    }
    
    public void setApprmt(String apprmt) {
        this.apprmt = apprmt;
    }
    
    @Column(name="APMRMT", length=30)
    public String getApmrmt() {
        return this.apmrmt;
    }
    
    public void setApmrmt(String apmrmt) {
        this.apmrmt = apmrmt;
    }
    
    @Column(name="NOMRMT", length=50)
    public String getNomrmt() {
        return this.nomrmt;
    }
    
    public void setNomrmt(String nomrmt) {
        this.nomrmt = nomrmt;
    }
    
    @Column(name="SIGRMT", length=10)
    public String getSigrmt() {
        return this.sigrmt;
    }
    
    public void setSigrmt(String sigrmt) {
        this.sigrmt = sigrmt;
    }
    
    @Column(name="DFTRMT")
    public Boolean getDftrmt() {
        return this.dftrmt;
    }
    
    public void setDftrmt(Boolean dftrmt) {
        this.dftrmt = dftrmt;
    }




}


