package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Serdoc generated by hbm2java
 */
@Entity
@Table(name="SERDOC"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Serdoc  implements java.io.Serializable {


     private String idser;
     private String idare;
     private String idtipdoc;
     private String ejeser;
     private String numser;
     private Boolean habser;

    public Serdoc() {
    }

	
    public Serdoc(String idser) {
        this.idser = idser;
    }
    public Serdoc(String idser, String idare, String idtipdoc, String ejeser, String numser, Boolean habser) {
       this.idser = idser;
       this.idare = idare;
       this.idtipdoc = idtipdoc;
       this.ejeser = ejeser;
       this.numser = numser;
       this.habser = habser;
    }
   
     @Id 
    
    @Column(name="IDSER", unique=true, nullable=false, length=12)
    public String getIdser() {
        return this.idser;
    }
    
    public void setIdser(String idser) {
        this.idser = idser;
    }
    
    @Column(name="IDARE", length=8)
    public String getIdare() {
        return this.idare;
    }
    
    public void setIdare(String idare) {
        this.idare = idare;
    }
    
    @Column(name="IDTIPDOC", length=4)
    public String getIdtipdoc() {
        return this.idtipdoc;
    }
    
    public void setIdtipdoc(String idtipdoc) {
        this.idtipdoc = idtipdoc;
    }
    
    @Column(name="EJESER", length=4)
    public String getEjeser() {
        return this.ejeser;
    }
    
    public void setEjeser(String ejeser) {
        this.ejeser = ejeser;
    }
    
    @Column(name="NUMSER", length=6)
    public String getNumser() {
        return this.numser;
    }
    
    public void setNumser(String numser) {
        this.numser = numser;
    }
    
    @Column(name="HABSER")
    public Boolean getHabser() {
        return this.habser;
    }
    
    public void setHabser(Boolean habser) {
        this.habser = habser;
    }




}


