package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Subtipo generated by hbm2java
 */
@Entity
@Table(name="SUBTIPO"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Subtipo  implements java.io.Serializable {


     private String idsubtip;
     private Tipo tipo;
     private String dessubtip;

    public Subtipo() {
    }

	
    public Subtipo(String idsubtip) {
        this.idsubtip = idsubtip;
    }
    public Subtipo(String idsubtip, Tipo tipo, String dessubtip) {
       this.idsubtip = idsubtip;
       this.tipo = tipo;
       this.dessubtip = dessubtip;
    }
   
     @Id 
    
    @Column(name="IDSUBTIP", unique=true, nullable=false, length=6)
    public String getIdsubtip() {
        return this.idsubtip;
    }
    
    public void setIdsubtip(String idsubtip) {
        this.idsubtip = idsubtip;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDTIP")
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="DESSUBTIP", length=60)
    public String getDessubtip() {
        return this.dessubtip;
    }
    
    public void setDessubtip(String dessubtip) {
        this.dessubtip = dessubtip;
    }




}


