package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipdoc generated by hbm2java
 */
@Entity
@Table(name="TIPDOC"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Tipdoc  implements java.io.Serializable {


     private String idtipdoc;
     private String destipdoc;
     private String sigtipdoc;
     private String grptipdoc;
     private Integer durtipdoc;
     private Boolean habtipdoc;

    public Tipdoc() {
    }

	
    public Tipdoc(String idtipdoc) {
        this.idtipdoc = idtipdoc;
    }
    public Tipdoc(String idtipdoc, String destipdoc, String sigtipdoc, String grptipdoc, Integer durtipdoc, Boolean habtipdoc) {
       this.idtipdoc = idtipdoc;
       this.destipdoc = destipdoc;
       this.sigtipdoc = sigtipdoc;
       this.grptipdoc = grptipdoc;
       this.durtipdoc = durtipdoc;
       this.habtipdoc = habtipdoc;
    }
   
     @Id 
    
    @Column(name="IDTIPDOC", unique=true, nullable=false, length=4)
    public String getIdtipdoc() {
        return this.idtipdoc;
    }
    
    public void setIdtipdoc(String idtipdoc) {
        this.idtipdoc = idtipdoc;
    }
    
    @Column(name="DESTIPDOC", length=50)
    public String getDestipdoc() {
        return this.destipdoc;
    }
    
    public void setDestipdoc(String destipdoc) {
        this.destipdoc = destipdoc;
    }
    
    @Column(name="SIGTIPDOC", length=10)
    public String getSigtipdoc() {
        return this.sigtipdoc;
    }
    
    public void setSigtipdoc(String sigtipdoc) {
        this.sigtipdoc = sigtipdoc;
    }
    
    @Column(name="GRPTIPDOC", length=20)
    public String getGrptipdoc() {
        return this.grptipdoc;
    }
    
    public void setGrptipdoc(String grptipdoc) {
        this.grptipdoc = grptipdoc;
    }
    
    @Column(name="DURTIPDOC")
    public Integer getDurtipdoc() {
        return this.durtipdoc;
    }
    
    public void setDurtipdoc(Integer durtipdoc) {
        this.durtipdoc = durtipdoc;
    }
    
    @Column(name="HABTIPDOC")
    public Boolean getHabtipdoc() {
        return this.habtipdoc;
    }
    
    public void setHabtipdoc(Boolean habtipdoc) {
        this.habtipdoc = habtipdoc;
    }




}


