package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name="TIPO"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Tipo  implements java.io.Serializable {


     private String idtip;
     private String destip;
     private String grptip;
     private Set<Subtipo> subtipos = new HashSet<Subtipo>(0);

    public Tipo() {
    }

	
    public Tipo(String idtip) {
        this.idtip = idtip;
    }
    public Tipo(String idtip, String destip, String grptip, Set<Subtipo> subtipos) {
       this.idtip = idtip;
       this.destip = destip;
       this.grptip = grptip;
       this.subtipos = subtipos;
    }
   
     @Id 
    
    @Column(name="IDTIP", unique=true, nullable=false, length=4)
    public String getIdtip() {
        return this.idtip;
    }
    
    public void setIdtip(String idtip) {
        this.idtip = idtip;
    }
    
    @Column(name="DESTIP", length=50)
    public String getDestip() {
        return this.destip;
    }
    
    public void setDestip(String destip) {
        this.destip = destip;
    }
    
    @Column(name="GRPTIP", length=20)
    public String getGrptip() {
        return this.grptip;
    }
    
    public void setGrptip(String grptip) {
        this.grptip = grptip;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipo")
    public Set<Subtipo> getSubtipos() {
        return this.subtipos;
    }
    
    public void setSubtipos(Set<Subtipo> subtipos) {
        this.subtipos = subtipos;
    }




}


