package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unimed generated by hbm2java
 */
@Entity
@Table(name="UNIMED"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Unimed  implements java.io.Serializable {


     private String idunimed;
     private String desunimed;
     private String sigunimed;
     private Boolean habunimed;

    public Unimed() {
    }

	
    public Unimed(String idunimed) {
        this.idunimed = idunimed;
    }
    public Unimed(String idunimed, String desunimed, String sigunimed, Boolean habunimed) {
       this.idunimed = idunimed;
       this.desunimed = desunimed;
       this.sigunimed = sigunimed;
       this.habunimed = habunimed;
    }
   
     @Id 
    
    @Column(name="IDUNIMED", unique=true, nullable=false, length=4)
    public String getIdunimed() {
        return this.idunimed;
    }
    
    public void setIdunimed(String idunimed) {
        this.idunimed = idunimed;
    }
    
    @Column(name="DESUNIMED", length=50)
    public String getDesunimed() {
        return this.desunimed;
    }
    
    public void setDesunimed(String desunimed) {
        this.desunimed = desunimed;
    }
    
    @Column(name="SIGUNIMED", length=30)
    public String getSigunimed() {
        return this.sigunimed;
    }
    
    public void setSigunimed(String sigunimed) {
        this.sigunimed = sigunimed;
    }
    
    @Column(name="HABUNIMED")
    public Boolean getHabunimed() {
        return this.habunimed;
    }
    
    public void setHabunimed(Boolean habunimed) {
        this.habunimed = habunimed;
    }




}


