package com.sblm.modelMP;
// Generated 10-jul-2013 10:36:31 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="dbo"
    ,catalog="DBINS"
)
public class Usuario  implements java.io.Serializable {


     private String idusr;
     private String nomusr;
     private String apeusr;
     private String pswusr;
     private Boolean habusr;

    public Usuario() {
    }

	
    public Usuario(String idusr) {
        this.idusr = idusr;
    }
    public Usuario(String idusr, String nomusr, String apeusr, String pswusr, Boolean habusr) {
       this.idusr = idusr;
       this.nomusr = nomusr;
       this.apeusr = apeusr;
       this.pswusr = pswusr;
       this.habusr = habusr;
    }
   
     @Id 
    
    @Column(name="IDUSR", unique=true, nullable=false, length=20)
    public String getIdusr() {
        return this.idusr;
    }
    
    public void setIdusr(String idusr) {
        this.idusr = idusr;
    }
    
    @Column(name="NOMUSR", length=50)
    public String getNomusr() {
        return this.nomusr;
    }
    
    public void setNomusr(String nomusr) {
        this.nomusr = nomusr;
    }
    
    @Column(name="APEUSR", length=50)
    public String getApeusr() {
        return this.apeusr;
    }
    
    public void setApeusr(String apeusr) {
        this.apeusr = apeusr;
    }
    
    @Column(name="PSWUSR", length=30)
    public String getPswusr() {
        return this.pswusr;
    }
    
    public void setPswusr(String pswusr) {
        this.pswusr = pswusr;
    }
    
    @Column(name="HABUSR")
    public Boolean getHabusr() {
        return this.habusr;
    }
    
    public void setHabusr(Boolean habusr) {
        this.habusr = habusr;
    }




}


