package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "AREA", schema = "dbo", catalog = "beneficenciadba")
public class Area implements java.io.Serializable {

	private String idare;
	private String desare;
	private String sigare;
	private Boolean opcareext;
	private String dirare;
	private String refare;
	private String conare;
	private String carare;
	private String telare;
	private String anxare;
	private String faxare;
	private String webare;
	private Boolean habare;
	private String anexo;
	private String codigoarea;
	private String descripcion;
	private String direccion;
	private String fax;
	private String sigla;
	private String telefono;
	private String web;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Area() {
	}

	public Area(String idare) {
		this.idare = idare;
	}

	public Area(String idare, String desare, String sigare, Boolean opcareext,
			String dirare, String refare, String conare, String carare,
			String telare, String anxare, String faxare, String webare,
			Boolean habare, String anexo, String codigoarea,
			String descripcion, String direccion, String fax, String sigla,
			String telefono, String web, Set<Usuario> usuarios) {
		this.idare = idare;
		this.desare = desare;
		this.sigare = sigare;
		this.opcareext = opcareext;
		this.dirare = dirare;
		this.refare = refare;
		this.conare = conare;
		this.carare = carare;
		this.telare = telare;
		this.anxare = anxare;
		this.faxare = faxare;
		this.webare = webare;
		this.habare = habare;
		this.anexo = anexo;
		this.codigoarea = codigoarea;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.fax = fax;
		this.sigla = sigla;
		this.telefono = telefono;
		this.web = web;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "IDARE", unique = true, nullable = false, length = 8)
	public String getIdare() {
		return this.idare;
	}

	public void setIdare(String idare) {
		this.idare = idare;
	}

	@Column(name = "DESARE", length = 80)
	public String getDesare() {
		return this.desare;
	}

	public void setDesare(String desare) {
		this.desare = desare;
	}

	@Column(name = "SIGARE", length = 24)
	public String getSigare() {
		return this.sigare;
	}

	public void setSigare(String sigare) {
		this.sigare = sigare;
	}

	@Column(name = "OPCAREEXT")
	public Boolean getOpcareext() {
		return this.opcareext;
	}

	public void setOpcareext(Boolean opcareext) {
		this.opcareext = opcareext;
	}

	@Column(name = "DIRARE", length = 100)
	public String getDirare() {
		return this.dirare;
	}

	public void setDirare(String dirare) {
		this.dirare = dirare;
	}

	@Column(name = "REFARE", length = 100)
	public String getRefare() {
		return this.refare;
	}

	public void setRefare(String refare) {
		this.refare = refare;
	}

	@Column(name = "CONARE", length = 50)
	public String getConare() {
		return this.conare;
	}

	public void setConare(String conare) {
		this.conare = conare;
	}

	@Column(name = "CARARE", length = 30)
	public String getCarare() {
		return this.carare;
	}

	public void setCarare(String carare) {
		this.carare = carare;
	}

	@Column(name = "TELARE", length = 10)
	public String getTelare() {
		return this.telare;
	}

	public void setTelare(String telare) {
		this.telare = telare;
	}

	@Column(name = "ANXARE", length = 10)
	public String getAnxare() {
		return this.anxare;
	}

	public void setAnxare(String anxare) {
		this.anxare = anxare;
	}

	@Column(name = "FAXARE", length = 10)
	public String getFaxare() {
		return this.faxare;
	}

	public void setFaxare(String faxare) {
		this.faxare = faxare;
	}

	@Column(name = "WEBARE", length = 100)
	public String getWebare() {
		return this.webare;
	}

	public void setWebare(String webare) {
		this.webare = webare;
	}

	@Column(name = "HABARE")
	public Boolean getHabare() {
		return this.habare;
	}

	public void setHabare(Boolean habare) {
		this.habare = habare;
	}

	@Column(name = "ANEXO", length = 10)
	public String getAnexo() {
		return this.anexo;
	}

	public void setAnexo(String anexo) {
		this.anexo = anexo;
	}

	@Column(name = "CODIGOAREA", length = 8)
	public String getCodigoarea() {
		return this.codigoarea;
	}

	public void setCodigoarea(String codigoarea) {
		this.codigoarea = codigoarea;
	}

	@Column(name = "DESCRIPCION", length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DIRECCION", length = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "FAX", length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "SIGLA", length = 24)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "TELEFONO", length = 10)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "WEB", length = 100)
	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
