package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Califica generated by hbm2java
 */
@Entity
@Table(name = "Califica", schema = "dbo", catalog = "beneficenciadba")
public class Califica implements java.io.Serializable {

	private int idcalifica;
	private Inquilino inquilino;
	private Integer calificacion;
	private String concepto;
	private String califica;

	public Califica() {
	}

	public Califica(int idcalifica) {
		this.idcalifica = idcalifica;
	}

	public Califica(int idcalifica, Inquilino inquilino, Integer calificacion,
			String concepto, String califica) {
		this.idcalifica = idcalifica;
		this.inquilino = inquilino;
		this.calificacion = calificacion;
		this.concepto = concepto;
		this.califica = califica;
	}

	@Id
	@Column(name = "IDCALIFICA", unique = true, nullable = false)
	public int getIdcalifica() {
		return this.idcalifica;
	}

	public void setIdcalifica(int idcalifica) {
		this.idcalifica = idcalifica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINQUILINO")
	public Inquilino getInquilino() {
		return this.inquilino;
	}

	public void setInquilino(Inquilino inquilino) {
		this.inquilino = inquilino;
	}

	@Column(name = "CALIFICACION")
	public Integer getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}

	@Column(name = "CONCEPTO", length = 100)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "CALIFICA", length = 100)
	public String getCalifica() {
		return this.califica;
	}

	public void setCalifica(String califica) {
		this.califica = califica;
	}

}
