package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cartera generated by hbm2java
 */
@Entity
@Table(name = "CARTERA", schema = "dbo", catalog = "beneficenciadba")
public class Cartera implements java.io.Serializable {

	private int idcartera;
	private Usuario usuario;
	private String tipolista;
	private String numero;
	private Boolean estado;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;
	private Set<Detallecartera> detallecarteras = new HashSet<Detallecartera>(0);
	private Set<Cuota> cuotas = new HashSet<Cuota>(0);

	public Cartera() {
	}

	public Cartera(int idcartera) {
		this.idcartera = idcartera;
	}

	public Cartera(int idcartera, Usuario usuario, String tipolista,
			String numero, Boolean estado, String usrcre, String usrmod,
			Date feccre, Date fecmod, Set<Detallecartera> detallecarteras,
			Set<Cuota> cuotas) {
		this.idcartera = idcartera;
		this.usuario = usuario;
		this.tipolista = tipolista;
		this.numero = numero;
		this.estado = estado;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.detallecarteras = detallecarteras;
		this.cuotas = cuotas;
	}

	@Id
	@Column(name = "IDCARTERA", unique = true, nullable = false)
	public int getIdcartera() {
		return this.idcartera;
	}

	public void setIdcartera(int idcartera) {
		this.idcartera = idcartera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIO")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "TIPOLISTA", length = 20)
	public String getTipolista() {
		return this.tipolista;
	}

	public void setTipolista(String tipolista) {
		this.tipolista = tipolista;
	}

	@Column(name = "NUMERO", length = 20)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "USRCRE", length = 100)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 100)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cartera")
	public Set<Detallecartera> getDetallecarteras() {
		return this.detallecarteras;
	}

	public void setDetallecarteras(Set<Detallecartera> detallecarteras) {
		this.detallecarteras = detallecarteras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cartera")
	public Set<Cuota> getCuotas() {
		return this.cuotas;
	}

	public void setCuotas(Set<Cuota> cuotas) {
		this.cuotas = cuotas;
	}

}
