package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallearbitrio generated by hbm2java
 */
@Entity
@Table(name = "DETALLEARBITRIO", schema = "dbo", catalog = "beneficenciadba")
public class Detallearbitrio implements java.io.Serializable {

	private int iddetallearbitrio;
	private Usuario usuario;
	private Arbitrio arbitrio;
	private Double montopagado;
	private Integer anio;
	private String periodo;
	private Date fecharegistro;
	private String periodoanio;
	private String periodofinal;
	private String periodoinicial;
	private String observacion;
	private Boolean moneda;

	public Detallearbitrio() {
	}

	public Detallearbitrio(int iddetallearbitrio) {
		this.iddetallearbitrio = iddetallearbitrio;
	}

	public Detallearbitrio(int iddetallearbitrio, Usuario usuario,
			Arbitrio arbitrio, Double montopagado, Integer anio,
			String periodo, Date fecharegistro, String periodoanio,
			String periodofinal, String periodoinicial, String observacion,
			Boolean moneda) {
		this.iddetallearbitrio = iddetallearbitrio;
		this.usuario = usuario;
		this.arbitrio = arbitrio;
		this.montopagado = montopagado;
		this.anio = anio;
		this.periodo = periodo;
		this.fecharegistro = fecharegistro;
		this.periodoanio = periodoanio;
		this.periodofinal = periodofinal;
		this.periodoinicial = periodoinicial;
		this.observacion = observacion;
		this.moneda = moneda;
	}

	@Id
	@Column(name = "IDDETALLEARBITRIO", unique = true, nullable = false)
	public int getIddetallearbitrio() {
		return this.iddetallearbitrio;
	}

	public void setIddetallearbitrio(int iddetallearbitrio) {
		this.iddetallearbitrio = iddetallearbitrio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIO")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDARBITRIO")
	public Arbitrio getArbitrio() {
		return this.arbitrio;
	}

	public void setArbitrio(Arbitrio arbitrio) {
		this.arbitrio = arbitrio;
	}

	@Column(name = "MONTOPAGADO", precision = 53, scale = 0)
	public Double getMontopagado() {
		return this.montopagado;
	}

	public void setMontopagado(Double montopagado) {
		this.montopagado = montopagado;
	}

	@Column(name = "ANIO")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "PERIODO", length = 50)
	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAREGISTRO", length = 23)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "PERIODOANIO", length = 10)
	public String getPeriodoanio() {
		return this.periodoanio;
	}

	public void setPeriodoanio(String periodoanio) {
		this.periodoanio = periodoanio;
	}

	@Column(name = "PERIODOFINAL", length = 20)
	public String getPeriodofinal() {
		return this.periodofinal;
	}

	public void setPeriodofinal(String periodofinal) {
		this.periodofinal = periodofinal;
	}

	@Column(name = "PERIODOINICIAL", length = 15)
	public String getPeriodoinicial() {
		return this.periodoinicial;
	}

	public void setPeriodoinicial(String periodoinicial) {
		this.periodoinicial = periodoinicial;
	}

	@Column(name = "OBSERVACION", length = 50)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "MONEDA")
	public Boolean getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Boolean moneda) {
		this.moneda = moneda;
	}

}
