package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MensajeflujodocumentoId generated by hbm2java
 */
@Embeddable
public class MensajeflujodocumentoId implements java.io.Serializable {

	private Integer idmensajeflujodocumento;
	private Integer idflujodocumento;
	private String contenido;
	private Boolean estado;
	private Date fechaenvio;
	private Integer idusuarioenvio;
	private String nombreusuarioenvio;

	public MensajeflujodocumentoId() {
	}

	public MensajeflujodocumentoId(Integer idmensajeflujodocumento,
			Integer idflujodocumento, String contenido, Boolean estado,
			Date fechaenvio, Integer idusuarioenvio, String nombreusuarioenvio) {
		this.idmensajeflujodocumento = idmensajeflujodocumento;
		this.idflujodocumento = idflujodocumento;
		this.contenido = contenido;
		this.estado = estado;
		this.fechaenvio = fechaenvio;
		this.idusuarioenvio = idusuarioenvio;
		this.nombreusuarioenvio = nombreusuarioenvio;
	}

	@Column(name = "IDMENSAJEFLUJODOCUMENTO")
	public Integer getIdmensajeflujodocumento() {
		return this.idmensajeflujodocumento;
	}

	public void setIdmensajeflujodocumento(Integer idmensajeflujodocumento) {
		this.idmensajeflujodocumento = idmensajeflujodocumento;
	}

	@Column(name = "IDFLUJODOCUMENTO")
	public Integer getIdflujodocumento() {
		return this.idflujodocumento;
	}

	public void setIdflujodocumento(Integer idflujodocumento) {
		this.idflujodocumento = idflujodocumento;
	}

	@Column(name = "CONTENIDO", length = 100)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "FECHAENVIO", length = 10)
	public Date getFechaenvio() {
		return this.fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

	@Column(name = "IDUSUARIOENVIO")
	public Integer getIdusuarioenvio() {
		return this.idusuarioenvio;
	}

	public void setIdusuarioenvio(Integer idusuarioenvio) {
		this.idusuarioenvio = idusuarioenvio;
	}

	@Column(name = "NOMBREUSUARIOENVIO", length = 100)
	public String getNombreusuarioenvio() {
		return this.nombreusuarioenvio;
	}

	public void setNombreusuarioenvio(String nombreusuarioenvio) {
		this.nombreusuarioenvio = nombreusuarioenvio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MensajeflujodocumentoId))
			return false;
		MensajeflujodocumentoId castOther = (MensajeflujodocumentoId) other;

		return ((this.getIdmensajeflujodocumento() == castOther
				.getIdmensajeflujodocumento()) || (this
				.getIdmensajeflujodocumento() != null
				&& castOther.getIdmensajeflujodocumento() != null && this
				.getIdmensajeflujodocumento().equals(
						castOther.getIdmensajeflujodocumento())))
				&& ((this.getIdflujodocumento() == castOther
						.getIdflujodocumento()) || (this.getIdflujodocumento() != null
						&& castOther.getIdflujodocumento() != null && this
						.getIdflujodocumento().equals(
								castOther.getIdflujodocumento())))
				&& ((this.getContenido() == castOther.getContenido()) || (this
						.getContenido() != null
						&& castOther.getContenido() != null && this
						.getContenido().equals(castOther.getContenido())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getFechaenvio() == castOther.getFechaenvio()) || (this
						.getFechaenvio() != null
						&& castOther.getFechaenvio() != null && this
						.getFechaenvio().equals(castOther.getFechaenvio())))
				&& ((this.getIdusuarioenvio() == castOther.getIdusuarioenvio()) || (this
						.getIdusuarioenvio() != null
						&& castOther.getIdusuarioenvio() != null && this
						.getIdusuarioenvio().equals(
								castOther.getIdusuarioenvio())))
				&& ((this.getNombreusuarioenvio() == castOther
						.getNombreusuarioenvio()) || (this
						.getNombreusuarioenvio() != null
						&& castOther.getNombreusuarioenvio() != null && this
						.getNombreusuarioenvio().equals(
								castOther.getNombreusuarioenvio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdmensajeflujodocumento() == null ? 0 : this
						.getIdmensajeflujodocumento().hashCode());
		result = 37
				* result
				+ (getIdflujodocumento() == null ? 0 : this
						.getIdflujodocumento().hashCode());
		result = 37 * result
				+ (getContenido() == null ? 0 : this.getContenido().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37
				* result
				+ (getFechaenvio() == null ? 0 : this.getFechaenvio()
						.hashCode());
		result = 37
				* result
				+ (getIdusuarioenvio() == null ? 0 : this.getIdusuarioenvio()
						.hashCode());
		result = 37
				* result
				+ (getNombreusuarioenvio() == null ? 0 : this
						.getNombreusuarioenvio().hashCode());
		return result;
	}

}
