package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "PERFIL", schema = "dbo", catalog = "beneficenciadba")
public class Perfil implements java.io.Serializable {

	private int idperfil;
	private Boolean estado;
	private String descripcionperfil;
	private String nombreperfil;
	private Date feccre;
	private Date fecmod;
	private String usrcre;
	private String usrmod;
	private Set<Perfilmodulo> perfilmodulos = new HashSet<Perfilmodulo>(0);
	private Set<Auditoria> auditorias = new HashSet<Auditoria>(0);
	private Set<Perfilusuario> perfilusuarios = new HashSet<Perfilusuario>(0);

	public Perfil() {
	}

	public Perfil(int idperfil) {
		this.idperfil = idperfil;
	}

	public Perfil(int idperfil, Boolean estado, String descripcionperfil,
			String nombreperfil, Date feccre, Date fecmod, String usrcre,
			String usrmod, Set<Perfilmodulo> perfilmodulos,
			Set<Auditoria> auditorias, Set<Perfilusuario> perfilusuarios) {
		this.idperfil = idperfil;
		this.estado = estado;
		this.descripcionperfil = descripcionperfil;
		this.nombreperfil = nombreperfil;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.perfilmodulos = perfilmodulos;
		this.auditorias = auditorias;
		this.perfilusuarios = perfilusuarios;
	}

	@Id
	@Column(name = "IDPERFIL", unique = true, nullable = false)
	public int getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(int idperfil) {
		this.idperfil = idperfil;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "DESCRIPCIONPERFIL", length = 100)
	public String getDescripcionperfil() {
		return this.descripcionperfil;
	}

	public void setDescripcionperfil(String descripcionperfil) {
		this.descripcionperfil = descripcionperfil;
	}

	@Column(name = "NOMBREPERFIL", length = 50)
	public String getNombreperfil() {
		return this.nombreperfil;
	}

	public void setNombreperfil(String nombreperfil) {
		this.nombreperfil = nombreperfil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@Column(name = "USRCRE", length = 50)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 50)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Perfilmodulo> getPerfilmodulos() {
		return this.perfilmodulos;
	}

	public void setPerfilmodulos(Set<Perfilmodulo> perfilmodulos) {
		this.perfilmodulos = perfilmodulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Auditoria> getAuditorias() {
		return this.auditorias;
	}

	public void setAuditorias(Set<Auditoria> auditorias) {
		this.auditorias = auditorias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Perfilusuario> getPerfilusuarios() {
		return this.perfilusuarios;
	}

	public void setPerfilusuarios(Set<Perfilusuario> perfilusuarios) {
		this.perfilusuarios = perfilusuarios;
	}

}
