package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Perfilusuario generated by hbm2java
 */
@Entity
@Table(name = "PERFILUSUARIO", schema = "dbo", catalog = "beneficenciadba")
public class Perfilusuario implements java.io.Serializable {

	private int idperfilusuario;
	private Perfil perfil;
	private Usuario usuario;
	private Date feccre;
	private Date fecmod;
	private String usrcre;
	private String usrmod;
	private Boolean activo;
	private Set<Flujodocumento> flujodocumentos = new HashSet<Flujodocumento>(0);

	public Perfilusuario() {
	}

	public Perfilusuario(int idperfilusuario) {
		this.idperfilusuario = idperfilusuario;
	}

	public Perfilusuario(int idperfilusuario, Perfil perfil, Usuario usuario,
			Date feccre, Date fecmod, String usrcre, String usrmod,
			Boolean activo, Set<Flujodocumento> flujodocumentos) {
		this.idperfilusuario = idperfilusuario;
		this.perfil = perfil;
		this.usuario = usuario;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.activo = activo;
		this.flujodocumentos = flujodocumentos;
	}

	@Id
	@Column(name = "IDPERFILUSUARIO", unique = true, nullable = false)
	public int getIdperfilusuario() {
		return this.idperfilusuario;
	}

	public void setIdperfilusuario(int idperfilusuario) {
		this.idperfilusuario = idperfilusuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPERFIL")
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIO")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@Column(name = "USRCRE", length = 50)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 50)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Column(name = "ACTIVO")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfilusuario")
	public Set<Flujodocumento> getFlujodocumentos() {
		return this.flujodocumentos;
	}

	public void setFlujodocumentos(Set<Flujodocumento> flujodocumentos) {
		this.flujodocumentos = flujodocumentos;
	}

}
