package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipointerior generated by hbm2java
 */
@Entity
@Table(name = "TIPOINTERIOR", schema = "dbo", catalog = "beneficenciadba")
public class Tipointerior implements java.io.Serializable {

	private int idtipointerior;
	private String descripcion;
	private Boolean estado;
	private Set<Upa> upas = new HashSet<Upa>(0);
	private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

	public Tipointerior() {
	}

	public Tipointerior(int idtipointerior) {
		this.idtipointerior = idtipointerior;
	}

	public Tipointerior(int idtipointerior, String descripcion, Boolean estado,
			Set<Upa> upas, Set<Inmueble> inmuebles) {
		this.idtipointerior = idtipointerior;
		this.descripcion = descripcion;
		this.estado = estado;
		this.upas = upas;
		this.inmuebles = inmuebles;
	}

	@Id
	@Column(name = "IDTIPOINTERIOR", unique = true, nullable = false)
	public int getIdtipointerior() {
		return this.idtipointerior;
	}

	public void setIdtipointerior(int idtipointerior) {
		this.idtipointerior = idtipointerior;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipointerior")
	public Set<Upa> getUpas() {
		return this.upas;
	}

	public void setUpas(Set<Upa> upas) {
		this.upas = upas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipointerior")
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

}
