package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipotitularidad generated by hbm2java
 */
@Entity
@Table(name = "TIPOTITULARIDAD", schema = "dbo", catalog = "beneficenciadba")
public class Tipotitularidad implements java.io.Serializable {

	private int idtipotitularidad;
	private String descripcion;
	private Boolean estado;
	private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

	public Tipotitularidad() {
	}

	public Tipotitularidad(int idtipotitularidad) {
		this.idtipotitularidad = idtipotitularidad;
	}

	public Tipotitularidad(int idtipotitularidad, String descripcion,
			Boolean estado, Set<Inmueble> inmuebles) {
		this.idtipotitularidad = idtipotitularidad;
		this.descripcion = descripcion;
		this.estado = estado;
		this.inmuebles = inmuebles;
	}

	@Id
	@Column(name = "IDTIPOTITULARIDAD", unique = true, nullable = false)
	public int getIdtipotitularidad() {
		return this.idtipotitularidad;
	}

	public void setIdtipotitularidad(int idtipotitularidad) {
		this.idtipotitularidad = idtipotitularidad;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipotitularidad")
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

}
