package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipodocumento generated by hbm2java
 */
@Entity
@Table(name = "TIPODOCUMENTO", schema = "dbo", catalog = "beneficenciadba")
public class Tipodocumento implements java.io.Serializable {

	private String idtipodoc;
	private String descripcion;
	private String sigtipdoc;
	private String grupo;
	private Integer durtipdoc;
	private Boolean habtipdoc;
	private String codigotipodoc;
	private String sigla;
	private Set<Documento> documentos = new HashSet<Documento>(0);

	public Tipodocumento() {
	}

	public Tipodocumento(String idtipodoc) {
		this.idtipodoc = idtipodoc;
	}

	public Tipodocumento(String idtipodoc, String descripcion,
			String sigtipdoc, String grupo, Integer durtipdoc,
			Boolean habtipdoc, String codigotipodoc, String sigla,
			Set<Documento> documentos) {
		this.idtipodoc = idtipodoc;
		this.descripcion = descripcion;
		this.sigtipdoc = sigtipdoc;
		this.grupo = grupo;
		this.durtipdoc = durtipdoc;
		this.habtipdoc = habtipdoc;
		this.codigotipodoc = codigotipodoc;
		this.sigla = sigla;
		this.documentos = documentos;
	}

	@Id
	@Column(name = "IDTIPODOC", unique = true, nullable = false, length = 4)
	public String getIdtipodoc() {
		return this.idtipodoc;
	}

	public void setIdtipodoc(String idtipodoc) {
		this.idtipodoc = idtipodoc;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SIGTIPDOC", length = 10)
	public String getSigtipdoc() {
		return this.sigtipdoc;
	}

	public void setSigtipdoc(String sigtipdoc) {
		this.sigtipdoc = sigtipdoc;
	}

	@Column(name = "GRUPO", length = 20)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	@Column(name = "DURTIPDOC")
	public Integer getDurtipdoc() {
		return this.durtipdoc;
	}

	public void setDurtipdoc(Integer durtipdoc) {
		this.durtipdoc = durtipdoc;
	}

	@Column(name = "HABTIPDOC")
	public Boolean getHabtipdoc() {
		return this.habtipdoc;
	}

	public void setHabtipdoc(Boolean habtipdoc) {
		this.habtipdoc = habtipdoc;
	}

	@Column(name = "CODIGOTIPODOC", length = 4)
	public String getCodigotipodoc() {
		return this.codigotipodoc;
	}

	public void setCodigotipodoc(String codigotipodoc) {
		this.codigotipodoc = codigotipodoc;
	}

	@Column(name = "SIGLA", length = 10)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipodocumento")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

}
