package com.sblm.model4;

// Generated 06-nov-2013 11:43:21 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubigeo generated by hbm2java
 */
@Entity
@Table(name = "UBIGEO", schema = "dbo", catalog = "beneficenciadba")
public class Ubigeo implements java.io.Serializable {

	private String ubigeo;
	private String depa;
	private String prov;
	private String dist;
	private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);
	private Set<Upa> upas = new HashSet<Upa>(0);

	public Ubigeo() {
	}

	public Ubigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	public Ubigeo(String ubigeo, String depa, String prov, String dist,
			Set<Inmueble> inmuebles, Set<Upa> upas) {
		this.ubigeo = ubigeo;
		this.depa = depa;
		this.prov = prov;
		this.dist = dist;
		this.inmuebles = inmuebles;
		this.upas = upas;
	}

	@Id
	@Column(name = "UBIGEO", unique = true, nullable = false, length = 6)
	public String getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(String ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "DEPA", length = 50)
	public String getDepa() {
		return this.depa;
	}

	public void setDepa(String depa) {
		this.depa = depa;
	}

	@Column(name = "PROV", length = 50)
	public String getProv() {
		return this.prov;
	}

	public void setProv(String prov) {
		this.prov = prov;
	}

	@Column(name = "DIST", length = 50)
	public String getDist() {
		return this.dist;
	}

	public void setDist(String dist) {
		this.dist = dist;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubigeo")
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubigeo")
	public Set<Upa> getUpas() {
		return this.upas;
	}

	public void setUpas(Set<Upa> upas) {
		this.upas = upas;
	}

}
