package com.sblm.model3;

// Generated 25/11/2013 12:19:12 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuentabancaria generated by hbm2java
 */
@Entity
@Table(name = "CUENTABANCARIA", schema = "dbo", catalog = "beneficenciadba")
public class Cuentabancaria implements java.io.Serializable {

	private int idcuentabancaria;
	private Banco banco;
	private String nroCuenta;
	private String moneda;
	private String cuentacontable;
	private String sihabilitado;
	private Date fechacreacion;
	private String usuariocreador;
	private Date fechamodificacion;
	private String usuariomodificador;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);

	public Cuentabancaria() {
	}

	public Cuentabancaria(int idcuentabancaria) {
		this.idcuentabancaria = idcuentabancaria;
	}

	public Cuentabancaria(int idcuentabancaria, Banco banco, String nroCuenta,
			String moneda, String cuentacontable, String sihabilitado,
			Date fechacreacion, String usuariocreador, Date fechamodificacion,
			String usuariomodificador, Set<Contrato> contratos) {
		this.idcuentabancaria = idcuentabancaria;
		this.banco = banco;
		this.nroCuenta = nroCuenta;
		this.moneda = moneda;
		this.cuentacontable = cuentacontable;
		this.sihabilitado = sihabilitado;
		this.fechacreacion = fechacreacion;
		this.usuariocreador = usuariocreador;
		this.fechamodificacion = fechamodificacion;
		this.usuariomodificador = usuariomodificador;
		this.contratos = contratos;
	}

	@Id
	@Column(name = "idcuentabancaria", unique = true, nullable = false)
	public int getIdcuentabancaria() {
		return this.idcuentabancaria;
	}

	public void setIdcuentabancaria(int idcuentabancaria) {
		this.idcuentabancaria = idcuentabancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idbanco")
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Column(name = "nroCuenta", length = 50)
	public String getNroCuenta() {
		return this.nroCuenta;
	}

	public void setNroCuenta(String nroCuenta) {
		this.nroCuenta = nroCuenta;
	}

	@Column(name = "moneda", length = 50)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "cuentacontable", length = 50)
	public String getCuentacontable() {
		return this.cuentacontable;
	}

	public void setCuentacontable(String cuentacontable) {
		this.cuentacontable = cuentacontable;
	}

	@Column(name = "sihabilitado", length = 10)
	public String getSihabilitado() {
		return this.sihabilitado;
	}

	public void setSihabilitado(String sihabilitado) {
		this.sihabilitado = sihabilitado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 23)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "USUARIOCREADOR", length = 50)
	public String getUsuariocreador() {
		return this.usuariocreador;
	}

	public void setUsuariocreador(String usuariocreador) {
		this.usuariocreador = usuariocreador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAMODIFICACION", length = 23)
	public Date getFechamodificacion() {
		return this.fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	@Column(name = "USUARIOMODIFICADOR", length = 50)
	public String getUsuariomodificador() {
		return this.usuariomodificador;
	}

	public void setUsuariomodificador(String usuariomodificador) {
		this.usuariomodificador = usuariomodificador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentabancaria")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

}
