package com.sblm.model;

// Generated 25-oct-2013 9:24:04 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Arbitrio generated by hbm2java
 */
@Entity
@Table(name = "ARBITRIO", schema = "dbo", catalog = "beneficenciadba")
public class Arbitrio implements java.io.Serializable {

	private int idarbitrio;
	private Inquilino inquilino;
	private Uso uso;
	private Contrato contrato;
	private String jravcalle;
	private String nro;
	private String intdtostand;
	private Boolean moneda;
	private Double monto;
	private String frecuenciapago;
	private String clave;
	private Integer idusuariocreador;
	private Date fechacreacion;
	private Double total;
	private String departamento;
	private String distrito;
	private String provincia;
	private Set<Archivodocumento> archivodocumentos = new HashSet<Archivodocumento>(
			0);
	private Set<Detallearbitrio> detallearbitrios = new HashSet<Detallearbitrio>(
			0);

	public Arbitrio() {
	}

	public Arbitrio(int idarbitrio) {
		this.idarbitrio = idarbitrio;
	}

	public Arbitrio(int idarbitrio, Inquilino inquilino, Uso uso,
			Contrato contrato, String jravcalle, String nro,
			String intdtostand, Boolean moneda, Double monto,
			String frecuenciapago, String clave, Integer idusuariocreador,
			Date fechacreacion, Double total, String departamento,
			String distrito, String provincia,
			Set<Archivodocumento> archivodocumentos,
			Set<Detallearbitrio> detallearbitrios) {
		this.idarbitrio = idarbitrio;
		this.inquilino = inquilino;
		this.uso = uso;
		this.contrato = contrato;
		this.jravcalle = jravcalle;
		this.nro = nro;
		this.intdtostand = intdtostand;
		this.moneda = moneda;
		this.monto = monto;
		this.frecuenciapago = frecuenciapago;
		this.clave = clave;
		this.idusuariocreador = idusuariocreador;
		this.fechacreacion = fechacreacion;
		this.total = total;
		this.departamento = departamento;
		this.distrito = distrito;
		this.provincia = provincia;
		this.archivodocumentos = archivodocumentos;
		this.detallearbitrios = detallearbitrios;
	}

	@Id @GeneratedValue
	@Column(name = "IDARBITRIO", unique = true, nullable = false)
	public int getIdarbitrio() {
		return this.idarbitrio;
	}

	public void setIdarbitrio(int idarbitrio) {
		this.idarbitrio = idarbitrio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINQUILINO")
	public Inquilino getInquilino() {
		return this.inquilino;
	}

	public void setInquilino(Inquilino inquilino) {
		this.inquilino = inquilino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSO")
	public Uso getUso() {
		return this.uso;
	}

	public void setUso(Uso uso) {
		this.uso = uso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCONTRATO")
	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	@Column(name = "JRAVCALLE", length = 50)
	public String getJravcalle() {
		return this.jravcalle;
	}

	public void setJravcalle(String jravcalle) {
		this.jravcalle = jravcalle;
	}

	@Column(name = "NRO", length = 10)
	public String getNro() {
		return this.nro;
	}

	public void setNro(String nro) {
		this.nro = nro;
	}

	@Column(name = "INTDTOSTAND", length = 50)
	public String getIntdtostand() {
		return this.intdtostand;
	}

	public void setIntdtostand(String intdtostand) {
		this.intdtostand = intdtostand;
	}

	@Column(name = "MONEDA")
	public Boolean getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Boolean moneda) {
		this.moneda = moneda;
	}

	@Column(name = "MONTO", precision = 53, scale = 0)
	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	@Column(name = "FRECUENCIAPAGO", length = 50)
	public String getFrecuenciapago() {
		return this.frecuenciapago;
	}

	public void setFrecuenciapago(String frecuenciapago) {
		this.frecuenciapago = frecuenciapago;
	}

	@Column(name = "CLAVE", length = 50)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "IDUSUARIOCREADOR")
	public Integer getIdusuariocreador() {
		return this.idusuariocreador;
	}

	public void setIdusuariocreador(Integer idusuariocreador) {
		this.idusuariocreador = idusuariocreador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACREACION", length = 23)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "TOTAL", precision = 53, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "DEPARTAMENTO", length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "DISTRITO", length = 50)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "PROVINCIA", length = 50)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arbitrio")
	public Set<Archivodocumento> getArchivodocumentos() {
		return this.archivodocumentos;
	}

	public void setArchivodocumentos(Set<Archivodocumento> archivodocumentos) {
		this.archivodocumentos = archivodocumentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arbitrio")
	public Set<Detallearbitrio> getDetallearbitrios() {
		return this.detallearbitrios;
	}

	public void setDetallearbitrios(Set<Detallearbitrio> detallearbitrios) {
		this.detallearbitrios = detallearbitrios;
	}

}
