package com.sblm.model;

// Generated 21-oct-2013 16:05:24 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Archivodocumento generated by hbm2java
 */
@Entity
@Table(name = "ARCHIVODOCUMENTO", schema = "dbo", catalog = "beneficenciadba")
public class Archivodocumento implements java.io.Serializable {

	private int idarchivodocumento;
	private Inquilino inquilino;
	private Carta carta;
	private Inmueble inmueble;
	private Documento documento;
	private Extensionarchivo extensionarchivo;
	private Upa upa;
	private Arbitrio arbitrio;
	private String tipodocumento;
	private String ruta;
	private String area;
	private Integer autorArchivo;
	private Date fechaCreacion;
	private String usuarioCreador;

	public Archivodocumento() {
	}

	public Archivodocumento(int idarchivodocumento) {
		this.idarchivodocumento = idarchivodocumento;
	}

	public Archivodocumento(int idarchivodocumento, Inquilino inquilino,
			Carta carta, Inmueble inmueble, Documento documento,
			Extensionarchivo extensionarchivo, Upa upa, Arbitrio arbitrio,
			String tipodocumento, String ruta, String area,
			Integer autorArchivo, Date fechaCreacion, String usuarioCreador) {
		this.idarchivodocumento = idarchivodocumento;
		this.inquilino = inquilino;
		this.carta = carta;
		this.inmueble = inmueble;
		this.documento = documento;
		this.extensionarchivo = extensionarchivo;
		this.upa = upa;
		this.arbitrio = arbitrio;
		this.tipodocumento = tipodocumento;
		this.ruta = ruta;
		this.area = area;
		this.autorArchivo = autorArchivo;
		this.fechaCreacion = fechaCreacion;
		this.usuarioCreador = usuarioCreador;
	}

	@Id @GeneratedValue
	@Column(name = "idarchivodocumento", unique = true, nullable = false)
	public int getIdarchivodocumento() {
		return this.idarchivodocumento;
	}

	public void setIdarchivodocumento(int idarchivodocumento) {
		this.idarchivodocumento = idarchivodocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINQUILINO")
	public Inquilino getInquilino() {
		return this.inquilino;
	}

	public void setInquilino(Inquilino inquilino) {
		this.inquilino = inquilino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCARTA")
	public Carta getCarta() {
		return this.carta;
	}

	public void setCarta(Carta carta) {
		this.carta = carta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINMUEBLE")
	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocumento")
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idExtensionArchivo")
	public Extensionarchivo getExtensionarchivo() {
		return this.extensionarchivo;
	}

	public void setExtensionarchivo(Extensionarchivo extensionarchivo) {
		this.extensionarchivo = extensionarchivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUPA")
	public Upa getUpa() {
		return this.upa;
	}

	public void setUpa(Upa upa) {
		this.upa = upa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDARBITRIO")
	public Arbitrio getArbitrio() {
		return this.arbitrio;
	}

	public void setArbitrio(Arbitrio arbitrio) {
		this.arbitrio = arbitrio;
	}

	@Column(name = "TIPODOCUMENTO", length = 50)
	public String getTipodocumento() {
		return this.tipodocumento;
	}

	public void setTipodocumento(String tipodocumento) {
		this.tipodocumento = tipodocumento;
	}

	@Column(name = "ruta", length = 100)
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	@Column(name = "area", length = 25)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "autorArchivo")
	public Integer getAutorArchivo() {
		return this.autorArchivo;
	}

	public void setAutorArchivo(Integer autorArchivo) {
		this.autorArchivo = autorArchivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaCreacion", length = 23)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "usuarioCreador", length = 50)
	public String getUsuarioCreador() {
		return this.usuarioCreador;
	}

	public void setUsuarioCreador(String usuarioCreador) {
		this.usuarioCreador = usuarioCreador;
	}

}
