package com.sblm.model;
// Generated 11/11/2013 06:03:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name="Banco"
    ,schema="dbo"
    ,catalog="beneficenciadba"
)
public class Banco  implements java.io.Serializable {


     private int idbanco;
     private String codigo;
     private String nombre;
     private String telefono;
     private String direccion;
     private String emailcontacto;
     private String paginaweb;
     private Date fechacreacion;
     private String usuariocreador;
     private Date fechamodificacion;
     private String usuariomodificador;
     private Set<Cuentabancaria> cuentabancarias = new HashSet<Cuentabancaria>(0);

    public Banco() {
    }

	
    public Banco(int idbanco) {
        this.idbanco = idbanco;
    }
    public Banco(int idbanco, String codigo, String nombre, String telefono, String direccion, String emailcontacto, String paginaweb, Date fechacreacion, String usuariocreador, Date fechamodificacion, String usuariomodificador, Set<Cuentabancaria> cuentabancarias) {
       this.idbanco = idbanco;
       this.codigo = codigo;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.emailcontacto = emailcontacto;
       this.paginaweb = paginaweb;
       this.fechacreacion = fechacreacion;
       this.usuariocreador = usuariocreador;
       this.fechamodificacion = fechamodificacion;
       this.usuariomodificador = usuariomodificador;
       this.cuentabancarias = cuentabancarias;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="idbanco", unique=true, nullable=false)
    public int getIdbanco() {
        return this.idbanco;
    }
    
    public void setIdbanco(int idbanco) {
        this.idbanco = idbanco;
    }
    
    @Column(name="codigo", length=100)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="nombre", length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="telefono", length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="direccion", length=200)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="emailcontacto", length=200)
    public String getEmailcontacto() {
        return this.emailcontacto;
    }
    
    public void setEmailcontacto(String emailcontacto) {
        this.emailcontacto = emailcontacto;
    }
    
    @Column(name="paginaweb", length=200)
    public String getPaginaweb() {
        return this.paginaweb;
    }
    
    public void setPaginaweb(String paginaweb) {
        this.paginaweb = paginaweb;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACREACION", length=23)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    
    @Column(name="USUARIOCREADOR", length=50)
    public String getUsuariocreador() {
        return this.usuariocreador;
    }
    
    public void setUsuariocreador(String usuariocreador) {
        this.usuariocreador = usuariocreador;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAMODIFICACION", length=23)
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }
    
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }
    
    @Column(name="USUARIOMODIFICADOR", length=50)
    public String getUsuariomodificador() {
        return this.usuariomodificador;
    }
    
    public void setUsuariomodificador(String usuariomodificador) {
        this.usuariomodificador = usuariomodificador;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="banco")
    public Set<Cuentabancaria> getCuentabancarias() {
        return this.cuentabancarias;
    }
    
    public void setCuentabancarias(Set<Cuentabancaria> cuentabancarias) {
        this.cuentabancarias = cuentabancarias;
    }




}


