package com.sblm.model;
// Generated 23/10/2013 04:24:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carta generated by hbm2java
 */
@Entity
@Table(name="CARTA"
    ,schema="dbo"
    ,catalog="beneficenciadba"
)
public class Carta  implements java.io.Serializable {


     private int idcarta;
     private Contrato contrato;
     private String distrito;
     private String jravcalle;
     private String nro;
     private String intdtostand;
     private String provincia;
     private String departamento;
     private Integer idusuariocreador;
     private Date fechacreacion;
     private Integer nroarchivos;
     private String clave;

    public Carta() {
    }

	
    public Carta(int idcarta) {
        this.idcarta = idcarta;
    }
    public Carta(int idcarta, Contrato contrato, String distrito, String jravcalle, String nro, String intdtostand, String provincia, String departamento, Integer idusuariocreador, Date fechacreacion, Integer nroarchivos,String clave) {
       this.idcarta = idcarta;
       this.contrato = contrato;
       this.distrito = distrito;
       this.jravcalle = jravcalle;
       this.nro = nro;
       this.intdtostand = intdtostand;
       this.provincia = provincia;
       this.departamento = departamento;
       this.idusuariocreador = idusuariocreador;
       this.fechacreacion = fechacreacion;
       this.nroarchivos = nroarchivos;
       this.clave=clave;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="IDCARTA", unique=true, nullable=false)
    public int getIdcarta() {
        return this.idcarta;
    }
    
    public void setIdcarta(int idcarta) {
        this.idcarta = idcarta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCONTRATO")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    
    @Column(name="CLAVE", length=50)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.distrito = clave;
    }
    
    @Column(name="JRAVCALLE", length=50)
    public String getJravcalle() {
        return this.jravcalle;
    }
    
    public void setJravcalle(String jravcalle) {
        this.jravcalle = jravcalle;
    }
    
    @Column(name="NRO", length=10)
    public String getNro() {
        return this.nro;
    }
    
    public void setNro(String nro) {
        this.nro = nro;
    }
    
    @Column(name="INTDTOSTAND", length=50)
    public String getIntdtostand() {
        return this.intdtostand;
    }
    
    public void setIntdtostand(String intdtostand) {
        this.intdtostand = intdtostand;
    }
    
    @Column(name="PROVINCIA", length=50)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    
    @Column(name="DEPARTAMENTO", length=50)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    
    @Column(name="IDUSUARIOCREADOR")
    public Integer getIdusuariocreador() {
        return this.idusuariocreador;
    }
    
    public void setIdusuariocreador(Integer idusuariocreador) {
        this.idusuariocreador = idusuariocreador;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHACREACION", length=23)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    
    @Column(name="NROARCHIVOS")
    public Integer getNroarchivos() {
        return this.nroarchivos;
    }
    
    public void setNroarchivos(Integer nroarchivos) {
        this.nroarchivos = nroarchivos;
    }




}


