package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallecartera generated by hbm2java
 */
@Entity
@Table(name = "DETALLECARTERA", schema = "dbo", catalog = "beneficenciadba")
public class Detallecartera implements java.io.Serializable {

	private int iddetallecartera;
	private Inmueble inmueble;
	private Uso uso;
	private Cartera cartera;
	private Upa upa;
	private Contrato contrato;
	private String numero;
	private BigDecimal rentasoles;
	private BigDecimal rentadolar;
	private BigDecimal mora;
	private Date fechavencimiento;
	private String moneda;
	private Boolean estado;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;

	public Detallecartera() {
	}

	public Detallecartera(int iddetallecartera, Date feccre) {
		this.iddetallecartera = iddetallecartera;
		this.feccre = feccre;
	}

	public Detallecartera(int iddetallecartera, Inmueble inmueble, Uso uso,
			Cartera cartera, Upa upa, Contrato contrato, String numero,
			BigDecimal rentasoles, BigDecimal rentadolar, BigDecimal mora,
			Date fechavencimiento, String moneda, Boolean estado,
			String usrcre, String usrmod, Date feccre, Date fecmod) {
		this.iddetallecartera = iddetallecartera;
		this.inmueble = inmueble;
		this.uso = uso;
		this.cartera = cartera;
		this.upa = upa;
		this.contrato = contrato;
		this.numero = numero;
		this.rentasoles = rentasoles;
		this.rentadolar = rentadolar;
		this.mora = mora;
		this.fechavencimiento = fechavencimiento;
		this.moneda = moneda;
		this.estado = estado;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
	}

	@Id @GeneratedValue
	@Column(name = "IDDETALLECARTERA", unique = true, nullable = false)
	public int getIddetallecartera() {
		return this.iddetallecartera;
	}

	public void setIddetallecartera(int iddetallecartera) {
		this.iddetallecartera = iddetallecartera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDINMUEBLE")
	public Inmueble getInmueble() {
		if(inmueble==null){
			inmueble=new Inmueble();
			}
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSO")
	public Uso getUso() {
		if(uso==null){
			uso=new Uso();
			}
		return this.uso;
	}

	public void setUso(Uso uso) {
		this.uso = uso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCARTERA")
	public Cartera getCartera() {
		if(cartera==null){
			cartera=new Cartera();
			}
		return this.cartera;
	}

	public void setCartera(Cartera cartera) {
		this.cartera = cartera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUPA")
	public Upa getUpa() {
		if(upa==null){
			upa=new Upa();
			}
		return this.upa;
	}

	public void setUpa(Upa upa) {
		this.upa = upa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCONTRATO")
	public Contrato getContrato() {
		if(contrato==null){
			contrato=new Contrato();
			}
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	@Column(name = "NUMERO", length = 15)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "RENTASOLES", precision = 9)
	public BigDecimal getRentasoles() {
		return this.rentasoles;
	}

	public void setRentasoles(BigDecimal rentasoles) {
		this.rentasoles = rentasoles;
	}

	@Column(name = "RENTADOLAR", precision = 9)
	public BigDecimal getRentadolar() {
		return this.rentadolar;
	}

	public void setRentadolar(BigDecimal rentadolar) {
		this.rentadolar = rentadolar;
	}

	@Column(name = "MORA", precision = 9)
	public BigDecimal getMora() {
		return this.mora;
	}

	public void setMora(BigDecimal mora) {
		this.mora = mora;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAVENCIMIENTO", length = 23)
	public Date getFechavencimiento() {
		return this.fechavencimiento;
	}

	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

	@Column(name = "MONEDA", length = 20)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "USRCRE", length = 100)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 100)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

}
