package com.sblm.model;

// Generated 28-oct-2013 10:49:25 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detallecuota generated by hbm2java
 */
@Entity
@Table(name = "DETALLECUOTA", schema = "dbo", catalog = "beneficenciadba")
public class Detallecuota implements java.io.Serializable {

	private int iddetallecuota;
	private Cuota cuota;
	private Double montosoles;
	private Date fecharegistro;
	private Double montodolar;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;
	private Double mora;
	private String observacion;
	private Boolean regularizacion;
	public Detallecuota() {
	}

	public Detallecuota(int iddetallecuota) {
		this.iddetallecuota = iddetallecuota;
	}

	public Detallecuota(int iddetallecuota, Cuota cuota, Double montosoles,
			Date fecharegistro, Double montodolar, String usrcre,
			String usrmod, Date feccre, Date fecmod, Double mora,
			String observacion, Boolean regularizacion) {
		this.iddetallecuota = iddetallecuota;
		this.cuota = cuota;
		this.montosoles = montosoles;
		this.fecharegistro = fecharegistro;
		this.montodolar = montodolar;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.mora = mora;
		this.observacion = observacion;
		this.regularizacion = regularizacion;
	}

	@Id @GeneratedValue
	@Column(name = "IDDETALLECUOTA", unique = true, nullable = false)
	public int getIddetallecuota() {
		return this.iddetallecuota;
	}

	public void setIddetallecuota(int iddetallecuota) {
		this.iddetallecuota = iddetallecuota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCUOTA")
	public Cuota getCuota() {
		if(cuota== null){
			cuota=new Cuota();
		}
		return this.cuota;
	}

	public void setCuota(Cuota cuota) {
		this.cuota = cuota;
	}

	@Column(name = "MONTOSOLES", precision = 53, scale = 0)
	public Double getMontosoles() {
		return this.montosoles;
	}

	public void setMontosoles(Double montosoles) {
		this.montosoles = montosoles;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAREGISTRO", length = 23)
	public Date getFecharegistro() {
		return this.fecharegistro;
	}

	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}

	@Column(name = "MONTODOLAR", precision = 53, scale = 0)
	public Double getMontodolar() {
		return this.montodolar;
	}

	public void setMontodolar(Double montodolar) {
		this.montodolar = montodolar;
	}

	@Column(name = "USRCRE", length = 50)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 50)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@Column(name = "MORA", precision = 53, scale = 0)
	public Double getMora() {
		return this.mora;
	}

	public void setMora(Double mora) {
		this.mora = mora;
	}

	@Column(name = "OBSERVACION", length = 300)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}
	@Column(name = "REGULARIZACION")
	public Boolean getRegularizacion() {
		return regularizacion;
	}

	public void setRegularizacion(Boolean regularizacion) {
		this.regularizacion = regularizacion;
	}

}
