package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Eventoauditoria generated by hbm2java
 */
@Entity
@Table(name = "EVENTOAUDITORIA", schema = "dbo", catalog = "beneficenciadba")
public class Eventoauditoria implements java.io.Serializable {

	private int ideventoauditoria;
	private String tipoevento;
	private Set<Auditoria> auditorias = new HashSet<Auditoria>(0);

	public Eventoauditoria() {
	}

	public Eventoauditoria(int ideventoauditoria) {
		this.ideventoauditoria = ideventoauditoria;
	}

	public Eventoauditoria(int ideventoauditoria, String tipoevento,
			Set<Auditoria> auditorias) {
		this.ideventoauditoria = ideventoauditoria;
		this.tipoevento = tipoevento;
		this.auditorias = auditorias;
	}

	@Id @GeneratedValue
	@Column(name = "IDEVENTOAUDITORIA", unique = true, nullable = false)
	public int getIdeventoauditoria() {
		return this.ideventoauditoria;
	}

	public void setIdeventoauditoria(int ideventoauditoria) {
		this.ideventoauditoria = ideventoauditoria;
	}

	@Column(name = "TIPOEVENTO", length = 200)
	public String getTipoevento() {
		return this.tipoevento;
	}

	public void setTipoevento(String tipoevento) {
		this.tipoevento = tipoevento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventoauditoria")
	public Set<Auditoria> getAuditorias() {
		return this.auditorias;
	}

	public void setAuditorias(Set<Auditoria> auditorias) {
		this.auditorias = auditorias;
	}

}
