package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Extensionarchivo generated by hbm2java
 */
@Entity
@Table(name = "EXTENSIONARCHIVO", schema = "dbo", catalog = "beneficenciadba")
public class Extensionarchivo implements java.io.Serializable {

	private int idExtensionArchivo;
	private String ext;
	private String descExt;
	private String rutaIcono;
	private Set<Archivodocumento> archivodocumentos = new HashSet<Archivodocumento>(
			0);

	public Extensionarchivo() {
	}

	public Extensionarchivo(int idExtensionArchivo) {
		this.idExtensionArchivo = idExtensionArchivo;
	}

	public Extensionarchivo(int idExtensionArchivo, String ext, String descExt,
			String rutaIcono, Set<Archivodocumento> archivodocumentos) {
		this.idExtensionArchivo = idExtensionArchivo;
		this.ext = ext;
		this.descExt = descExt;
		this.rutaIcono = rutaIcono;
		this.archivodocumentos = archivodocumentos;
	}

	@Id @GeneratedValue
	@Column(name = "idExtensionArchivo", unique = true, nullable = false)
	public int getIdExtensionArchivo() {
		return this.idExtensionArchivo;
	}

	public void setIdExtensionArchivo(int idExtensionArchivo) {
		this.idExtensionArchivo = idExtensionArchivo;
	}

	@Column(name = "ext", length = 5)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "descExt", length = 15)
	public String getDescExt() {
		return this.descExt;
	}

	public void setDescExt(String descExt) {
		this.descExt = descExt;
	}

	@Column(name = "rutaIcono", length = 100)
	public String getRutaIcono() {
		return this.rutaIcono;
	}

	public void setRutaIcono(String rutaIcono) {
		this.rutaIcono = rutaIcono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "extensionarchivo")
	public Set<Archivodocumento> getArchivodocumentos() {
		return this.archivodocumentos;
	}

	public void setArchivodocumentos(Set<Archivodocumento> archivodocumentos) {
		this.archivodocumentos = archivodocumentos;
	}

}
