package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Materialpredominante generated by hbm2java
 */
@Entity
@Table(name = "MATERIALPREDOMINANTE", schema = "dbo", catalog = "beneficenciadba")
public class Materialpredominante implements java.io.Serializable {

	private int idmaterialpredominante;
	private String descripcion;
	private Boolean estado;
	private Set<Inmueble> inmuebles = new HashSet<Inmueble>(0);

	public Materialpredominante() {
	}

	public Materialpredominante(int idmaterialpredominante) {
		this.idmaterialpredominante = idmaterialpredominante;
	}

	public Materialpredominante(int idmaterialpredominante, String descripcion,
			Boolean estado, Set<Inmueble> inmuebles) {
		this.idmaterialpredominante = idmaterialpredominante;
		this.descripcion = descripcion;
		this.estado = estado;
		this.inmuebles = inmuebles;
	}

	@Id @GeneratedValue
	@Column(name = "IDMATERIALPREDOMINANTE", unique = true, nullable = false)
	public int getIdmaterialpredominante() {
		return this.idmaterialpredominante;
	}

	public void setIdmaterialpredominante(int idmaterialpredominante) {
		this.idmaterialpredominante = idmaterialpredominante;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materialpredominante")
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

}
