package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paginamodulo generated by hbm2java
 */
@Entity
@Table(name = "PAGINAMODULO", schema = "dbo", catalog = "beneficenciadba")
public class Paginamodulo implements java.io.Serializable {

	private int idpaginamodulo;
	private Pagina pagina;
	private Modulo modulo;
	private Date fecha;
	private Boolean estado;
	private String valortabla;

	public Paginamodulo() {
	}

	public Paginamodulo(int idpaginamodulo) {
		this.idpaginamodulo = idpaginamodulo;
	}

	public Paginamodulo(int idpaginamodulo, Pagina pagina, Modulo modulo,
			Date fecha, Boolean estado, String valortabla) {
		this.idpaginamodulo = idpaginamodulo;
		this.pagina = pagina;
		this.modulo = modulo;
		this.fecha = fecha;
		this.estado = estado;
		this.valortabla = valortabla;
	}

	@Id @GeneratedValue
	@Column(name = "IDPAGINAMODULO", unique = true, nullable = false)
	public int getIdpaginamodulo() {
		return this.idpaginamodulo;
	}

	public void setIdpaginamodulo(int idpaginamodulo) {
		this.idpaginamodulo = idpaginamodulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPAGINA")
	public Pagina getPagina() {
		if(pagina==null){
			pagina=new Pagina();
			}
		return this.pagina;
	}

	public void setPagina(Pagina pagina) {
		this.pagina = pagina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMODULO")
	public Modulo getModulo() {
		if(modulo==null){
			modulo=new Modulo();
			}
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "VALORTABLA", length = 10)
	public String getValortabla() {
		return this.valortabla;
	}

	public void setValortabla(String valortabla) {
		this.valortabla = valortabla;
	}

}
