package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seguimientoflujo generated by hbm2java
 */
@Entity
@Table(name = "SEGUIMIENTOFLUJO", schema = "dbo", catalog = "beneficenciadba")
public class Seguimientoflujo implements java.io.Serializable {

	private int idsegflujodocumento;
	private Flujodocumento flujodocumento;
	private Usuario usuario;
	private String estado;
	private Date fecharecepcion;
	private Integer idusuarioremitente;
	private String respuesta;
	private Date fechaaprobacionrechazo;
	private String comentario;
	private Date fecharaprobacionrechazo;
	private Integer idperfilusuario;

	public Seguimientoflujo() {
	}

	public Seguimientoflujo(int idsegflujodocumento) {
		this.idsegflujodocumento = idsegflujodocumento;
	}

	public Seguimientoflujo(int idsegflujodocumento,
			Flujodocumento flujodocumento, Usuario usuario, String estado,
			Date fecharecepcion, Integer idusuarioremitente, String respuesta,
			Date fechaaprobacionrechazo, String comentario,
			Date fecharaprobacionrechazo, Integer idperfilusuario) {
		this.idsegflujodocumento = idsegflujodocumento;
		this.flujodocumento = flujodocumento;
		this.usuario = usuario;
		this.estado = estado;
		this.fecharecepcion = fecharecepcion;
		this.idusuarioremitente = idusuarioremitente;
		this.respuesta = respuesta;
		this.fechaaprobacionrechazo = fechaaprobacionrechazo;
		this.comentario = comentario;
		this.fecharaprobacionrechazo = fecharaprobacionrechazo;
		this.idperfilusuario = idperfilusuario;
	}
 
	@Id @GeneratedValue
	@Column(name = "IDSEGFLUJODOCUMENTO", unique = true, nullable = false)
	public int getIdsegflujodocumento() {
		return this.idsegflujodocumento;
	}

	public void setIdsegflujodocumento(int idsegflujodocumento) {
		this.idsegflujodocumento = idsegflujodocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDFLUJODOCUMENTO")
	public Flujodocumento getFlujodocumento() {
		if(flujodocumento==null){
			flujodocumento=new Flujodocumento();
			}
		return this.flujodocumento;
	}

	public void setFlujodocumento(Flujodocumento flujodocumento) {
		this.flujodocumento = flujodocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUSUARIODESTINO")
	public Usuario getUsuario() {
		if(usuario==null){
			usuario=new Usuario();
			}
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ESTADO", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHARECEPCION", length = 23)
	public Date getFecharecepcion() {
		return this.fecharecepcion;
	}

	public void setFecharecepcion(Date fecharecepcion) {
		this.fecharecepcion = fecharecepcion;
	}

	@Column(name = "IDUSUARIOREMITENTE")
	public Integer getIdusuarioremitente() {
		return this.idusuarioremitente;
	}

	public void setIdusuarioremitente(Integer idusuarioremitente) {
		this.idusuarioremitente = idusuarioremitente;
	}

	@Column(name = "RESPUESTA", length = 10)
	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHAAPROBACIONRECHAZO", length = 23)
	public Date getFechaaprobacionrechazo() {
		return this.fechaaprobacionrechazo;
	}

	public void setFechaaprobacionrechazo(Date fechaaprobacionrechazo) {
		this.fechaaprobacionrechazo = fechaaprobacionrechazo;
	}

	@Column(name = "COMENTARIO", length = 100)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHARAPROBACIONRECHAZO", length = 23)
	public Date getFecharaprobacionrechazo() {
		return this.fecharaprobacionrechazo;
	}

	public void setFecharaprobacionrechazo(Date fecharaprobacionrechazo) {
		this.fecharaprobacionrechazo = fecharaprobacionrechazo;
	}

	@Column(name = "IDPERFILUSUARIO")
	public Integer getIdperfilusuario() {
		return this.idperfilusuario;
	}

	public void setIdperfilusuario(Integer idperfilusuario) {
		this.idperfilusuario = idperfilusuario;
	}

}
