package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipoentidad generated by hbm2java
 */
@Entity
@Table(name = "TIPOENTIDAD", schema = "dbo", catalog = "beneficenciadba")
public class Tipoentidad implements java.io.Serializable {

	private int idtipoentidad;
	private String descripcion;
	private Boolean estado;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;
	private Set<Inquilino> inquilinos = new HashSet<Inquilino>(0);

	public Tipoentidad() {
	}

	public Tipoentidad(int idtipoentidad) {
		this.idtipoentidad = idtipoentidad;
	}

	public Tipoentidad(int idtipoentidad, String descripcion, Boolean estado,
			String usrcre, String usrmod, Date feccre, Date fecmod,
			Set<Inquilino> inquilinos) {
		this.idtipoentidad = idtipoentidad;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.inquilinos = inquilinos;
	}

	@Id @GeneratedValue
	@Column(name = "IDTIPOENTIDAD", unique = true, nullable = false)
	public int getIdtipoentidad() {
		return this.idtipoentidad;
	}

	public void setIdtipoentidad(int idtipoentidad) {
		this.idtipoentidad = idtipoentidad;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "USRCRE", length = 100)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 100)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoentidad")
	public Set<Inquilino> getInquilinos() {
		return this.inquilinos;
	}

	public void setInquilinos(Set<Inquilino> inquilinos) {
		this.inquilinos = inquilinos;
	}

}
