package com.sblm.model;

// Generated 28-oct-2013 15:02:56 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipocontrato generated by hbm2java
 */
@Entity
@Table(name = "TIPOCONTRATO", schema = "dbo", catalog = "beneficenciadba")
public class Tipocontrato implements java.io.Serializable {

	private int idtipocontrato;
	private String descripcion;
	private Boolean estado;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;

	public Tipocontrato() {
	}

	public Tipocontrato(int idtipocontrato) {
		this.idtipocontrato = idtipocontrato;
	}

	public Tipocontrato(int idtipocontrato, String descripcion, Boolean estado,
			String usrcre, String usrmod, Date feccre, Date fecmod) {
		this.idtipocontrato = idtipocontrato;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
	}

	@Id
	@Column(name = "IDTIPOCONTRATO", unique = true, nullable = false)
	public int getIdtipocontrato() {
		return this.idtipocontrato;
	}

	public void setIdtipocontrato(int idtipocontrato) {
		this.idtipocontrato = idtipocontrato;
	}

	@Column(name = "DESCRIPCION", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "USRCRE", length = 50)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "USRMOD", length = 50)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECCRE", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECMOD", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

}
