package com.sblm.model;

// Generated 14-oct-2013 14:58:03 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uso generated by hbm2java
 */
@Entity
@Table(name = "USO", schema = "dbo", catalog = "beneficenciadba")
public class Uso implements java.io.Serializable {

	private int iduso;
	private String descripcion;
	private String usrcre;
	private String usrmod;
	private Date feccre;
	private Date fecmod;
	private Set<Upa> upas = new HashSet<Upa>(0);
	private Set<Detallecartera> detallecarteras = new HashSet<Detallecartera>(0);
	private Set<Arbitrio> arbitrios = new HashSet<Arbitrio>(0);

	public Uso() {
	}

	public Uso(int iduso) {
		this.iduso = iduso;
	}

	public Uso(int iduso, String descripcion, String usrcre, String usrmod,
			Date feccre, Date fecmod, Set<Upa> upas,
			Set<Detallecartera> detallecarteras, Set<Arbitrio> arbitrios) {
		this.iduso = iduso;
		this.descripcion = descripcion;
		this.usrcre = usrcre;
		this.usrmod = usrmod;
		this.feccre = feccre;
		this.fecmod = fecmod;
		this.upas = upas;
		this.detallecarteras = detallecarteras;
		this.arbitrios = arbitrios;
	}

	@Id @GeneratedValue
	@Column(name = "iduso", unique = true, nullable = false)
	public int getIduso() {
		return this.iduso;
	}

	public void setIduso(int iduso) {
		this.iduso = iduso;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "usrcre", length = 50)
	public String getUsrcre() {
		return this.usrcre;
	}

	public void setUsrcre(String usrcre) {
		this.usrcre = usrcre;
	}

	@Column(name = "usrmod", length = 50)
	public String getUsrmod() {
		return this.usrmod;
	}

	public void setUsrmod(String usrmod) {
		this.usrmod = usrmod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "feccre", length = 23)
	public Date getFeccre() {
		return this.feccre;
	}

	public void setFeccre(Date feccre) {
		this.feccre = feccre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecmod", length = 23)
	public Date getFecmod() {
		return this.fecmod;
	}

	public void setFecmod(Date fecmod) {
		this.fecmod = fecmod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uso")
	public Set<Upa> getUpas() {
		return this.upas;
	}

	public void setUpas(Set<Upa> upas) {
		this.upas = upas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uso")
	public Set<Detallecartera> getDetallecarteras() {
		return this.detallecarteras;
	}

	public void setDetallecarteras(Set<Detallecartera> detallecarteras) {
		this.detallecarteras = detallecarteras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "uso")
	public Set<Arbitrio> getArbitrios() {
		return this.arbitrios;
	}

	public void setArbitrios(Set<Arbitrio> arbitrios) {
		this.arbitrios = arbitrios;
	}

}
